### ISSUE TITLE
黑名单建议

### ISSUE THREAD

**Issue by LolveyRuby** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#101]
建议在黑名单中添加chatGPT，否则只能用白名单，这样的话，对于速度比较慢的节点来说，比较影响日常使用。

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/9c79dc87ca8af18260d0fe108620d2fbe5d48a39
