### ISSUE TITLE
please add rules for paramount plus

### ISSUE THREAD

**Issue by Johnpenglee** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#106]
paramount plus app can’t be used, please add a proxy rule for the domain suffix paramount plus.com

**Comment by Johnshall** [comment]
plus.com 似乎会被重定向到 plus.net，然后是一个卖宽带的业务？似乎不太正确。

**Comment by Johnpenglee** [comment]
抱歉是我写错了，网址是paramountplus.com，我自己添加这个域名后paramount plus就可以用了

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/074b7abf70954000cbf963e2592d45f74d5364d0
