### ISSUE TITLE
自动更新规则的问题

### ISSUE THREAD

**Issue by aniure** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#11]
步骤一：安装捷径，并填写规则文件地址。
这一步在捷径里哪里填写规则文件地址，能不能具体说一下。

**Comment by Johnshall** [comment]
比如：
黑名单+去广告规则：https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_banlist_ad.conf
白名单+去广告规则：https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_whitelist_ad.conf

**Comment by Johnshall** [comment]
首先，第一次导入规则的时候会显示一个问题，在那里可以填写地址；
或者点击快捷指令右上角的三个点，在第二个文本框中填写地址。

**Comment by aniure** [comment]
这个快捷指令应该怎么设置？主要是这里没看懂。

**Comment by aniure** [comment]
> 首先，第一次导入规则的时候会显示一个问题，在那里可以填写地址； 或者点击快捷指令右上角的三个点，在第二个文本框中填写地址。

研究了下懒人规则自动更新的捷径，发现规则文件和这个捷径是配合使用的，懒人规则里有“## 您可以在此处插入自定义规则”，而捷径里也有对应的步骤用自定义的规则来替换，所以希望你的规则里增加这个内容，便于增加自定义规则。

**Comment by aniure** [comment]
![Uploading 85E57FDD-35D5-4390-AF85-C7D42962D6DD.png…]()

**Comment by aniure** [comment]
![1BD4D4E4-7645-4C69-85F9-FD95EEF9E55D](https://user-images.githubusercontent.com/47635135/165214370-a6affd46-cc62-4d7b-9da5-14119d873b46.png)
研究了下懒人规则自动更新的捷径，发现规则文件和这个捷径是配合使用的，懒人规则里有“## 您可以在此处插入自定义规则”，而捷径里也有对应的步骤用自定义的规则来替换，所以希望你的规则里增加这个内容，便于增加自定义规则。

**Comment by Johnshall** [comment]
感谢您建设性的意见！
首先，本脚本是利用x-callback-urls实现更新规则的，降低了内存占用，且不会弹窗警告。但这样设计不涉及对文本内容的读取和修改，而使用x-callback-urls并修改文件内容可能需要文件服务器等更复杂的操作，我不太确定这是否可以实现，也没有很多时间去研究这个。
  **自定义规则可以通过扩展配置，或直接在原规则中Rule项加入规则url即可（注意格式），使用脚本更新不会覆盖这部分的配置。**
  很抱歉，最近太忙无暇进行更多的更新，欢迎讨论和pr！
  祝万事胜意！

**Comment by aniure** [comment]
> 

我尝试把捷径截图里箭头所指的内容改成你这个规则里本身已有的注释语句，也可以实现增加自定义规则的效果。

**Comment by aniure** [comment]
> 首先，第一次导入规则的时候会显示一个问题，在那里可以填写地址； 或者点击快捷指令右上角的三个点，在第二个文本框中填写地址。

这个在懒人规则那个捷径里是填文本，不是 url。

**Comment by Johnshall** [comment]
> 我尝试把捷径截图里箭头所指的内容改成你这个规则里本身已有的注释语句，也可以实现增加自定义规则的效果。

是的，用懒人规则捷径可以用于更新本规则，但是无法自动更新（需要点一下）。本项目的捷径可以自动更新，也可以通过https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/issues/11#issuecomment-1109345356 方式来对其他规则进行更新。

**Comment by Johnshall** [comment]
最简单的方法是点击规则->编辑纯文本，在[Rule]下添加规则地址，例如 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Advertising/Advertising.list

**Comment by aniure** [comment]
> 最简单的方法是点击规则->编辑纯文本，在[Rule]下添加规则地址，例如 https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Advertising/Advertising.list

这种方法不够方便，比如有一些比较小众的网站就无法实现。

**Comment by Johnshall** [comment]
为什么无法实现？在这个场景里只需要按照格式把网站设置成代理/直连/阻断就行了，根本不用外挂规则

**Comment by aniure** [comment]
> 为什么无法实现？在这个场景里只需要按照格式把网站设置成代理/直连/阻断就行了，根本不用外挂规则

在文本编辑里直接添加的话，更新后会覆盖手动添加的内容。

**Comment by Johnshall** [comment]
> > 为什么无法实现？在这个场景里只需要按照格式把网站设置成代理/直连/阻断就行了，根本不用外挂规则
> 
> 在文本编辑里直接添加的话，更新后会覆盖手动添加的内容。

那就点一下配置文件，选扩展配置，在扩展配置里写

**Comment by Johnshall** [comment]
我想这个问题已经被解决，因此关闭这个讨论；
如果关于这个问题有新的疑问，欢迎重新打开。

**Comment by tianzhich** [comment]
你好，我有点没看懂这个扩展配置，这里点击以后，好像和新增了一个配置没啥区别，也不是在现有这个配置扩展。现在有没有什么办法可以增加自定义规则，并且避免更新的时候覆盖呢？
