### ISSUE TITLE
“跳过代理”不定时失效

### ISSUE THREAD

**Issue by tumblemelon** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#112]
发现“跳过代理”这一规则，刚切换配置或者开启代理开关的时候是有效的，建行生活等软件能够正常使用。但是过一段时间后，再打开建行生活就会提示检测到开启了代理。这时候关闭再打开代理开关，或者把原来的配置再重新选择切换一遍，就可以了。这是为什么呢？

**Comment by Johnshall** [comment]
可能和 Shadowrocket 的处理有关。 @wlxuf

**Comment by Johnshall** [comment]
点击配置文件后面ⓘ-通用-「跳过代理」的列表中添加：
*.ccb.com
