### ISSUE TITLE
Linkin自动连接国内网站

### ISSUE THREAD

**Issue by seek2now** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#114]
能否国内访问不跳转linkedin.cn

**Comment by Johnshall** [comment]
你在用哪个规则？

**Comment by seek2now** [comment]
国内外划分

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/67b2c9531621fc93999ff42e509686991836933d
