### ISSUE TITLE
请求app弹窗提示不安全代理而无法使用，尽管已经屏蔽广告的解决

### ISSUE THREAD

**Issue by sumanzi** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#115]

**Comment by Johnshall** [comment]
某些app是通过检测是否通过代理，这个无法用屏蔽广告解决。
可以试试在这里做修改：https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/blob/release/lazy_group.conf#L25
