### ISSUE TITLE
好像有很久去除不了广告了

### ISSUE THREAD

**Issue by kuko7** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#116]
每天都会更新规则
刚刚更新完之后实测
知乎 微博 b站 QQ音乐这些还是有开屏广告
而且好像我这个情况已经很久了
请问是我设置出了问题还是现在的规则没办法屏蔽广告了呀？

**Comment by Johnshall** [comment]
玄学问题 https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/issues/6#issuecomment-1019313202
