### ISSUE TITLE
Google重定向

### ISSUE THREAD

**Issue by FridayAnubis** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#119]
IOS的google默认搜索引擎是google.cn，这个众所周知早就没法用了
作者能不能在规则里加入重定向google.cn到google.com呢
自己加的话每次更新规则就没了

**Comment by Johnshall** [comment]
我比较好奇你加了什么？

**Comment by FridayAnubis** [comment]
从v2ray的重定向粘贴过来的？
不过这个问题我还是通过改变iOS地区解决了，如果没有更多事情的话可以Close啦。

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/blob/release/lazy_group.conf#L216
url重定向本来就有。可能是你没有开启https解密或者没有正确安装证书。
