### ISSUE TITLE
weibo IP 显示没有改变

### ISSUE THREAD

**Issue by mangojuice123** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#12]
使用了全局代理 + 去广告的规则，但是打开手机 weibo，ip 显示仍为本地，不是服务器所在地址，请问这个如何解决呢？

**Comment by mangojuice123** [comment]
破案了，小火箭版本升级下就好

**Comment by Johnshall** [comment]
哈哈

**Comment by mangojuice123** [comment]
> 哈哈

抖音上抓了几个包，`zijieapi.com`, `douyinpic.com` 等等域名我都按照设置的规则（纯白名单，500个左右，其他即使 `.cn` `.CN `结尾的也要走代理）测试了一下，测试结果是走代理，但是实际用抖音的时候，显示的 ip 地址还是正常的 ip 地址，这个老哥有什么方法解决下吗

**Comment by Johnshall** [comment]
> 抖音上抓了几个包，`zijieapi.com`, `douyinpic.com` 等等域名我都按照设置的规则（纯白名单，500个左右，其他即使 `.cn` `.CN `结尾的也要走代理）测试了一下，测试结果是走代理，但是实际用抖音的时候，显示的 ip 地址还是正常的 ip 地址，这个老哥有什么方法解决下吗

可以用wireshark之类的工具抓一下抖音全部的流量交互地址。我想这应该是个很复杂的工作。
或者您可以将500个白名单进行等距拆分，逐一排查ip验证的域名在哪个区间，当然这适用于单一域名查验，多域名还是比较麻烦。
如果可以，希望您继续在此issue追踪您的研究进展，我也会尽绵薄之力。

**Comment by mangojuice123** [comment]
> > 抖音上抓了几个包，`zijieapi.com`, `douyinpic.com` 等等域名我都按照设置的规则（纯白名单，500个左右，其他即使 `.cn` `.CN `结尾的也要走代理）测试了一下，测试结果是走代理，但是实际用抖音的时候，显示的 ip 地址还是正常的 ip 地址，这个老哥有什么方法解决下吗
> 
> 可以用wireshark之类的工具抓一下抖音全部的流量交互地址。我想这应该是个很复杂的工作。 或者您可以将500个白名单进行等距拆分，逐一排查ip验证的域名在哪个区间，当然这适用于单一域名查验，多域名还是比较麻烦。 如果可以，希望您继续在此issue追踪您的研究进展，我也会尽绵薄之力。

好的，感谢指点，我试试看 :)

**Comment by Johnshall** [comment]
我将关闭此问题。如果您还有疑问，可以继续留言。
期待您的继续跟进。
