### ISSUE TITLE
国内外区分+去广告的那个，没法看油管，能进去，但是没法播放视频，视频卡在封面

### ISSUE THREAD

**Issue by kumuweifengchun-sudo** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#122]

**Comment by kumuweifengchun-sudo** [comment]
国内外区分+去广告的那个，没法看油管，能进去，但是没法播放视频，视频卡在封面

**Comment by kumuweifengchun-sudo** [comment]
好像不只是那个，其他的白名单，黑名单都是

**Comment by kumuweifengchun-sudo** [comment]
开起了https解析，就出现这种情况

**Comment by Johnshall** [comment]
抱歉，没有复现。请你更新到最新版本试试？或者试着提供更多的细节：比如无法播放视频的时候，日志里是否会出现很多 Reject？

**Comment by kumuweifengchun-sudo** [comment]
我如果开起了HTTPS解析后，它打开油管，它它就有很多都reject了，如果没开HTTPS解析就不多(已经更新到了最新版)

**Comment by Johnshall** [comment]
可以提供一些关键的被Reject的地址吗？

**Comment by Johnshall** [comment]
我无法复现

**Comment by dannychen0109** [comment]
我的情况差不多，不开启HTTPS解密，所有app可以正常上，但是开启HTTPS解密，需要翻的app就全部没有网络，但在浏览器可以正常打开。

**Comment by Johnshall** [comment]
很奇怪，这是否是小火箭的问题？
这里好像也看到了：https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/issues/129#issue-1631321489

**Comment by Mr-ZhangL** [comment]
> 我的情况差不多，不开启HTTPS解密，所有app可以正常上，但是开启HTTPS解密，需要翻的app就全部没有网络，但在浏览器可以正常打开。

模块有问题，自行排查一下
