### ISSUE TITLE
New Bing需要用代理才能使用Chat，可否在“国内外划分”中增加Bing的链接为代理？

### ISSUE THREAD

**Issue by Really-well** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#125]
New Bing需要用代理才能使用Chat，否则直接链接的话可以连接，但是没有chat，可否将Bing相关的在“国内外划分”规则中，将Bing相关的链接改为代理？
谢谢！

**Comment by Johnshall** [comment]
如果直接将这条规则加入可能会影响使用bing国内版的用户
你可以试着在规则界面点击编辑纯文本，然后将以下内容加进最前面。
```
DOMAIN-SUFFIX,bing.com,PROXY
```

**Comment by Really-well** [comment]
非常感谢，已经解决问题了。在纯文本按如下方式编辑，更改了我的“国内外划分”规则，在该规则下，可以对Bing使用代理，可以使用Chat了。
![image](https://user-images.githubusercontent.com/128007304/225789524-82aa9583-056f-4b8a-befe-e517fa7fa228.png)

**Comment by mario-huang** [comment]
> 如果直接将这条规则加入可能会影响使用bing国内版的用户 你可以试着在规则界面点击编辑纯文本，然后将以下内容加进最前面。
> 
> ```
> DOMAIN-SUFFIX,bing.com,PROXY
> ```

但是每次更新规则后又要重新添加一次。
我认为没有人会喜欢用国内版bing吧，建议把它添加进去。
或者，懒人版可以正常使用new bing，但是又缺少去广告。请问能加入去广告吗？

**Comment by mario-huang** [comment]
@Johnshall 补充一下我的看法。
1、能找到这个仓库的人不大可能满足于国内版bing。
2、如果一定要照顾国内版bing，可以两个一起加上。
`DOMAIN-SUFFIX,bing.com,PROXY`
`DOMAIN-SUFFIX,cn.bing.com,DIRECT`

**Comment by Really-well** [comment]
> > 如果直接将这条规则加入可能会影响使用bing国内版的用户 你可以试着在规则界面点击编辑纯文本，然后将以下内容加进最前面。
> > ```
> > DOMAIN-SUFFIX,bing.com,PROXY
> > ```
> 
> 但是每次更新规则后又要重新添加一次。 我认为没有人会喜欢用国内版bing吧，建议把它添加进去。 或者，懒人版可以正常使用new bing，但是又缺少去广告。请问能加入去广告吗？

谢谢关注！
“但是每次更新规则后又要重新添加一次。”这个问题是又参考国内版规则，单独建了一个新的代理bing的规则。
“2、如果一定要照顾国内版bing，可以两个一起加上。
DOMAIN-SUFFIX,bing.com,PROXY
DOMAIN-SUFFIX,cn.bing.com,DIRECT“  这个主意很好，类似的网站问题也可以类似解决。

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/f3ccbb3a5c75d55b92d4a739f14db71a290233c9

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/f89b2cb89ab6b56d2b6be78e4b26c8e827787c4b

**Comment by mario-huang** [comment]
> [f89b2cb](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/f89b2cb89ab6b56d2b6be78e4b26c8e827787c4b)

It works, so many thks.

**Comment by fwilyair** [comment]
> > 如果直接将这条规则加入可能会影响使用bing国内版的用户 你可以试着在规则界面点击编辑纯文本，然后将以下内容加进最前面。
> > ```
> > DOMAIN-SUFFIX,bing.com,PROXY
> > ```
> 
> 但是每次更新规则后又要重新添加一次。 我认为没有人会喜欢用国内版bing吧，建议把它添加进去。 或者，懒人版可以正常使用new bing，但是又缺少去广告。请问能加入去广告吗？

我让ChatGPT帮我写了一个python，每次运行的时候自动获取一遍规则，然后把现在有的规则删了，把新的粘贴进去，再把我一个专门手动增加的规则合并进去
