### ISSUE TITLE
建行生活app不能使用

### ISSUE THREAD

**Issue by iMaezz** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#127]
每次都要关闭代理才能打开，跳过代理网址也没用

**Comment by Johnshall** [comment]
这似乎是小火箭的问题。请提交给开发者。
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/issues/112#issue-1590613695

**Comment by Johnshall** [comment]
点击配置文件后面ⓘ-通用-「跳过代理」的列表中添加：
*.ccb.com
