### ISSUE TITLE
 HTTPS 解密 之后facebook&ins&Twitter打不开

### ISSUE THREAD

**Issue by dannychen0109** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#128]
我开启 HTTPS 解密 之后，以下app没有网络

**Comment by dannychen0109** [comment]
facebook
ins
twitter
telegram

**Comment by Metaphorme** [comment]
规则的https解密只涉及：*.google.cn,*.googlevideo.com,*.tiktokv.com,*.byteoversea.com,*.tik-tokapi.com
其他的不会出问题。
telegram用的私有协议+ip，不涉及https。如果无法使用考虑一下是否是节点故障。
谢谢。

**Comment by Johnshall** [comment]
规则的https解密只涉及：.google.cn,.googlevideo.com,.tiktokv.com,.byteoversea.com,*.tik-tokapi.com
其他的不会出问题。
telegram用的私有协议+ip，不涉及https。如果无法使用考虑一下是否是节点故障。
谢谢。
