### ISSUE TITLE
转：HTTPS 解密 之后facebook&ins&Twitter打不开

### ISSUE THREAD

**Issue by Johnshall** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#129]
@dannychen0109
我开启 HTTPS 解密 之后，以下app没有网络：
facebook
ins
twitter
telegram

答：
规则的https解密只涉及：.google.cn,.googlevideo.com,.tiktokv.com,.byteoversea.com,*.tik-tokapi.com
其他的不会出问题。
telegram用的私有协议+ip，不涉及https。如果无法使用考虑一下是否是节点故障。

**Comment by dannychen0109** [comment]
同一个节点，只要我不开https解密，都可以使用。
但是这种情况仅限app，我如果打开https解密，用网页打开，但是正常的

**Comment by jackzzs** [comment]
> 同一个节点，只要我不开https解密，都可以使用。

出现类似情况，望修复。

使用的规则是lazy_group.conf
