### ISSUE TITLE
维护一个仅有去AD的规则可好？

### ISSUE THREAD

**Issue by mrshyi** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#13]
规则仅需：包括自定义的广告过滤规则，针对 iOS 端的网页广告、App 广告和视频广告；

当前分类：规则+去Ad、全局规则+去Ad、规则
缺：去Ad

辛苦大佬了

**Comment by Johnshall** [comment]
我不太懂你的意思。
仅去广告，其他的流量怎么办？规则里已经有了去广告+直连和去广告+代理。
期待你的回复。

**Comment by mrshyi** [comment]
主要是想作为单独规则使用，自己自由组合各种规则使用，当前去ad和其他规则集成到一起了，其他流量按需配置其他规则，比如这个独立去ad的规则：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list，但这个规则不全

**Comment by Johnshall** [comment]
所有广告在这里：
https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/master/factory/resultant/ad.list
如果可以的话，你可以手动拉取这个列表，在后面加入 Reject 即可。
这是个不错的功能，但是我最近比较忙，如果着急的话欢迎pr！

**Comment by Johnshall** [comment]
所有广告在这里：
https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/master/factory/resultant/ad.list
如果可以的话，你可以手动拉取这个列表，在后面加入 Reject 即可。
这是个不错的功能，但是我生病了，需要离开了，如果可以的话欢迎pr！

**Comment by Johnshall** [comment]
已加入 https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/9779687043270165d60bd3fde5ae41f8d4109df0
