### ISSUE TITLE
萌新求助！！我想给某个 App 添加代理如何实现？

### ISSUE THREAD

**Issue by sukbearai** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#135]
我使用的规则是懒人配置含策略组，我正在使用国外的一款 App ，发现它的流量策略是直连，我想修改成代理策略我应该怎么操作呢？

**Comment by kumuweifengchun-sudo** [comment]
什么软件？第一种你可以尝试用白名单，不常见的域名都走的代理，第二种就是你自己添加代理，如果不知道app域名的话你可以用浏览器搜他的官网，然后在小火箭配置里面点击测试规则，输入他的域名，然后你就可以看到它的走的模式是什么，如果策略那里写的是DIRECT，你就点添加域名到规则然后点保存就行
