### ISSUE TITLE
懒人规则能否支持ChatGPT

### ISSUE THREAD

**Issue by JoeMartini** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#137]
试了下懒人规则时，如果走配置，chatGPT会提示access dined，不知道是否有方式优化

**Comment by Johnshall** [comment]
这是节点的问题。你设置成“全局代理”也是这样的。

**Comment by JoeMartini** [comment]
并不是，改成全局后就可以正常访问了

**Comment by JoeMartini** [comment]
我也切换几个节点试过，现象都是一致的

**Comment by KagoJoker999** [comment]
我也是这个问题，希望大佬能够调整一下懒人模式🥹

**Comment by KagoJoker999** [comment]
Newbing也不能正常使用。

**Comment by 2048920439** [comment]
懒人模式里已经支持了啊,需要自己设置成可以使用的节点.我把懒人模式里相关的配置复制到Clash能够正常使用

**Comment by 2048920439** [comment]
> Newbing也不能正常使用。

newBing只需要这么配置一下就可以了 DOMAIN-KEYWORD,bing,PROXY
