### ISSUE TITLE
ios最新快捷指令如何自动更新呢

### ISSUE THREAD

**Issue by 1015572358** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#14]
最新的快捷指令按照作者说的更新无法自动更新

**Comment by Johnshall** [comment]
请参考 [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md) 进行提问。

**Comment by Johnshall** [comment]
我将关闭此问题。如果您还有疑问，可以继续留言。
