### ISSUE TITLE
用了规则之后访问国内的视频app不能联网，但是网页可以正常看，像抖音这种都不能正常浏览，请问怎么解决？

### ISSUE THREAD

**Issue by YiYoYe** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#140]

**Comment by YiYoYe** [comment]
老哥，还有个问题，我添加规则自动更新的时候没有快捷指令，应该是在软件里没有加入吗？我想请教一下怎么才能把更新规则加入到捷径里面。![image](https://user-images.githubusercontent.com/130005611/230270628-d1d9a4ae-5d39-4d98-a485-10a2ee04026f.png)

**Comment by YJL12345** [comment]
我也没有规则更新的选项，只有一个订阅更新

**Comment by YiYoYe** [comment]
> 我也没有规则更新的选项，只有一个订阅更新

是啊，不知道怎么添加规则更新呢
