### ISSUE TITLE
tiktok没网

### ISSUE THREAD

**Issue by JacobCao15** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#143]
懒人配置Https解密里*.tiktokv.com,*.byteoversea.com,*.tik-tokapi.com这些是干什么用的，我的iPad直接下的titok没有网络，删掉这些才能用titok，还有懒人配置是不是没有去广告啊，YouTube每次打开都有广告

**Comment by Johnshall** [comment]
1、解密TikTok相关域名是为了配合重写规则实现免拔卡观看TikTok。iPad能直接看的话就不需要此操作，删除相关域名即可。
2、懒人配置没有去广告的功能。
