### ISSUE TITLE
白名单+广告添加chat.forefront.ai域名

### ISSUE THREAD

**Issue by sorangegu** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#149]
可以在白名单+广告那里添加一个chat.forefront.ai域名吗，因为现在chatgpt挺火的，想让这个域名直接走代理

**Comment by fwilyair** [comment]
自己手动添加一下不就行了吗

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/88fe7159bafafe4f7870c18450847e62baee51d1
