### ISSUE TITLE
建议把t.co域名从广告列表去掉

### ISSUE THREAD

**Issue by zhangyulai** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#15]
t.co是twitter的短域名，现在的规则是reject，导致在twitter app里无法直接打开链接。
建议改为proxy

**Comment by Johnshall** [comment]
好的，这应该是一个上游问题，我会排查这个故障。感谢您的issue！

**Comment by Johnshall** [comment]
Fixed https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/ea0b1142fdf5af4378ca3448adffc0f3502460af
