### ISSUE TITLE
请教仅去广告规则如何与其他配置联用

### ISSUE THREAD

**Issue by Nicked639** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#159]
如题，本人对Shadowrocket不熟悉，下面遇到的问题还请不吝赐教。

仅去广告规则中不包括其他代理配置，而该规则提供的是一个.conf而不是.module，如果启用仅去广告规则，则会占用其他代理配置，我想请教一下如何方便的将仅去广告规则内容与其他代理配置进行联用呢？

我想到的一个办法是将其他配置文件纯文本复制到仅去广告规则的配置文件内，但是这既不优雅也不方便后续更新，请问还有更好的办法吗？ 如果将仅去广告规则做成模块，是否会更方便使用？

**Comment by Johnshall** [comment]
先在 Shadowrocket 中单独下载 sr_ad_only.conf，然后在正在使用的conf配置文件中加入 include=sr_ad_only.conf 就可以了。
请参考：https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/blob/release/lazy_group.conf#L54

**Comment by Nicked639** [comment]
> 先在 Shadowrocket 中单独下载 sr_ad_only.conf，然后在正在使用的conf配置文件中加入 include=sr_ad_only.conf 就可以了。
> 
> 请参考：https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/blob/release/lazy_group.conf#L54

谢谢解答🙏
