### ISSUE TITLE
使用较大规则导致游戏延迟变高

### ISSUE THREAD

**Issue by sixgodfan** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#16]
亲测，用这个规则玩和平精英导致网络不好，ping很高，玩不了游戏的地步（白+去广告，其他的没试），关闭就正常，什么情况？

**Comment by Johnshall** [comment]
游戏的流量需要经过shadowrocket处理分析然后出站，白名单内容较多，普通浏览网页时产生的延迟几乎无感知（相比于严格的TCP握手和加密解密过程）。而对于游戏这种特殊场景，分析过程产生的延迟会变的明显。  
  
建议在玩游戏时不要使用小火箭，如需要加速外服游戏，可以使用全局代理或内容较少的规则。
