### ISSUE TITLE
国内外ip划分 apple maps无法正常加载

### ISSUE THREAD

**Issue by lifeRebe1** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#162]
使用国内外划分规则时Apple Maps还有查找中的地图无法正常加载

**Comment by Johnshall** [comment]
在规则开头加入 DOMAIN-SUFFIX,apple.com,DIRECT 试试？

**Comment by lifeRebe1** [comment]
> 

嗯嗯改完没问题了，应该是本地DNS解析出来时国内IP，走代理会被服务端拦截
