### ISSUE TITLE
个别规则影响iOS自带“地图”应用

### ISSUE THREAD

**Issue by lmkyl** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#164]
“黑名单过滤”和“国内外划分”：影响
“懒人配置”：不影响
其他规则未测试

**Comment by lmkyl** [comment]
以上三个配置还影响“亚马逊购物”App

**Comment by lmkyl** [comment]
建议规则对amazon做区分，cn用direct，jp用proxy，而不是通通proxy

**Comment by Johnshall** [comment]
最近有些忙。请问可以请你pr到build分支吗？
