### ISSUE TITLE
懒人配置里 最后的这个js是干什么用的？

### ISSUE THREAD

**Issue by toyo2333** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#166]
懒人配置里 最后的这个js是干什么用的？

[Script]
# BoxJs安装脚本。
Rewrite: BoxJs = type=http-request,pattern=https?:\/\/boxjs\.(com|net),script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js, requires-body=true, timeout=120

看不懂

**Comment by Lonense** [comment]
可以查看下这个网站 https://docs.boxjs.app ，有一些比较有意思的脚本可以订阅。

**Comment by RabbitStar01** [comment]
我也纳闷是做什么用的，没看懂介绍，😂
