### ISSUE TITLE
感谢大佬！我找到一个top500的网站

### ISSUE THREAD

**Issue by mskgroup** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#17]
https://moz.com/top500
可以在这里下载csc格式的top500列表，是免费的
https://moz.com/top-500/download/?table=top500Domains
然后可以根据csv格式来处理top500网站

**Comment by Johnshall** [comment]
非常感谢您的贡献！
我会在晚一些的时间进行更新，并在这里追踪进度

**Comment by mskgroup** [comment]
我已经完成了咳咳咳，我去申请合并

**Comment by Johnshall** [comment]
感谢您的贡献！很抱歉由于我做了一些修改导致了冲突，原 pr 无法被直接merge，但保持了您的开发者身份。
过程可以在这里被追踪：https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/pull/18
祝生活愉快！

**Comment by mskgroup** [comment]
十分感谢！！

**Comment by Johnshall** [comment]
加油加油呀！
