### ISSUE TITLE
建议加入以下内容

### ISSUE THREAD

**Issue by PandaFiredoge** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#171]
DOMAIN-SUFFIX,mozilla.org,PROXY
DOMAIN-SUFFIX,wikimirror.net,DIRECT
DOMAIN-SUFFIX,wikimirror.org,DIRECT
DOMAIN-SUFFIX,txt.fyi,PROXY
DOMAIN-SUFFIX,adobe.com,PROXY
DOMAIN-SUFFIX,bing.com,PROXY
DOMAIN-SUFFIX,cn.bing.com,DIRECT
DOMAIN-SUFFIX,aol.com,PROXY
DOMAIN-SUFFIX,yahoo.com,PROXY

**Comment by PandaFiredoge** [comment]
另，建议PROXY苹果新闻

**Comment by chenpey** [comment]
非常希望能添加这两个 
DOMAIN-SUFFIX,qlogo.cn,DIRECT
DOMAIN-SUFFIX,qpic.cn,DIRECT

**Comment by PandaFiredoge** [comment]
顶

**Comment by PandaFiredoge** [comment]
顶

**Comment by Johnshall** [comment]
> 苹果新闻

苹果新闻是什么？

**Comment by Johnshall** [comment]
已更新，感谢指正。

**Comment by PandaFiredoge** [comment]
苹果新闻就是这个https://imgur.com/a/10ffsU6

**Comment by PandaFiredoge** [comment]
好像炸了https://th.bing.com/th/id/R.a20ce0e51c598912c2d763a07fa1d9bd?rik=5wJbPIF%2fxvznnA&riu=http%3a%2f%2fe0.ifengimg.com%2f04%2f2019%2f0630%2f4A2F00BF02E0F6822537EC71E9747DD955A9A4B6_size541_w3328_h1697.jpeg&ehk=8GAO5fuyWj97lAGm%2frtp%2bD%2b9osrgPGPHFihwNZCJWgY%3d&risl=&pid=ImgRaw&r=0
