### ISSUE TITLE
我可以定期提供最新的 top500 榜单

### ISSUE THREAD

**Issue by RealnodeVpn** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#173]
麻烦提供联系方式沟通一下。

**Comment by Johnshall** [comment]
谢谢。请按照以下文件的格式pr到这个文件。
https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/build/factory/resultant/top500_manual.list
