### ISSUE TITLE
去广告规则有格式错误，持续20多天了

### ISSUE THREAD

**Issue by WongAlice** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#174]
**去广告规则**在以下两个段落有“**重复嵌套**”错误，已持续20多天，没有人发现吗？

外面一层 “DOMAIN-SUFFIX,” 与 “,Reject” 多余了。
❶
```
# > Youku & Tudou
DOMAIN-SUFFIX,DOMAIN-SUFFIX,actives.youku.com,REJECT,Reject
DOMAIN-SUFFIX,DOMAIN-SUFFIX,ad.api.3g.tudou.com,REJECT,Reject
…
```

❷
```
# URL-REGEX,https?://.+.atm.youku.com,REJEC
# > Youtube
DOMAIN-SUFFIX,DOMAIN-SUFFIX,azabu-u.ac.jp,REJECT,Reject
…
```

**Comment by Johnshall** [comment]
抱歉，没有仔细审核pr，现已修复。

**Comment by WongAlice** [comment]
> 抱歉，没有仔细审核pr，现已修复。

还有多余的"_domain-suffix,_" 没有删除

```
DOMAIN-SUFFIX,domain-suffix,ACTIVES.YOUKU.COM,REJECT
```

**Comment by Johnshall** [comment]
> > 抱歉，没有仔细审核pr，现已修复。
> 
> 还有多余的"_domain-suffix,_" 没有删除
> 
> ```
> DOMAIN-SUFFIX,domain-suffix,ACTIVES.YOUKU.COM,REJECT
> ```

现在似乎没有了。抱歉之前生病了一直没看消息。
