### ISSUE TITLE
也没加呀

### ISSUE THREAD

**Issue by PandaFiredoge** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#175]
DOMAIN-SUFFIX,mozilla.org,PROXY
DOMAIN-SUFFIX,wikimirror.net,DIRECT
DOMAIN-SUFFIX,wikimirror.org,DIRECT
DOMAIN-SUFFIX,txt.fyi,PROXY
DOMAIN-SUFFIX,adobe.com,PROXY
DOMAIN-SUFFIX,bing.com,PROXY
DOMAIN-SUFFIX,cn.bing.com,DIRECT
DOMAIN-SUFFIX,aol.com,PROXY
DOMAIN-SUFFIX,yahoo.com,PROXY

**Comment by Johnshall** [comment]
看这个
https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/release/sr_top500_banlist_ad.conf

里面有
```
# Mozilla
DOMAIN-SUFFIX,mozilla.org,Proxy
# Txt.fyi
DOMAIN-SUFFIX,txt.fyi,Proxy
# Adobe
DOMAIN-SUFFIX,adobe.com,Proxy
# AOL
DOMAIN-SUFFIX,aol.com,Proxy
# Yahoo
DOMAIN-SUFFIX,yahoo.com,Proxy
```

**Comment by PandaFiredoge** [comment]
ok

**Comment by PandaFiredoge** [comment]
那必应呢

**Comment by Johnshall** [comment]
bing 很早就加了。
```
# New Bing
DOMAIN-SUFFIX,bing.com,Proxy
```

**Comment by PandaFiredoge** [comment]
黑名单有，白名单没有

**Comment by Johnshall** [comment]
白名单怎么没有呢？

**Comment by PandaFiredoge** [comment]
现在有了
DOMAIN-SUFFIX,mozilla.org,PROXY
DOMAIN-SUFFIX,wikimirror.net,DIRECT
DOMAIN-SUFFIX,wikimirror.org,DIRECT
DOMAIN-SUFFIX,txt.fyi,PROXY
DOMAIN-SUFFIX,adobe.com,PROXY
DOMAIN-SUFFIX,bing.com,PROXY
DOMAIN-SUFFIX,cn.bing.com,DIRECT
DOMAIN-SUFFIX,aol.com,PROXY
DOMAIN-SUFFIX,yahoo.com,PROXY
