### ISSUE TITLE
Linkedin区分错误

### ISSUE THREAD

**Issue by lucky-beans** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#177]
国际域名Linkedin.com被错误划分为国内域名没经过代理，事实上国内域名是Linkedin.cn而且已经停服打不开了，而且com不代理会自动跳转到cn类似Google。所以Linkedin.com和Linkedin.cn都需要设置为国外域名并代理。

**Comment by Johnshall** [comment]
Thanks!
