### ISSUE TITLE
关于去广告规则的疑惑

### ISSUE THREAD

**Issue by Yi-Xio** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#179]
大佬好，我发现在某些广告过滤规则中，很多按域名后缀匹配的规则，域名后缀的前面都多写了一个点，如下图所示。
![image](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/54212380/7db77d1a-937f-46c5-a44d-065cf7faff97)
我利用小火箭的”测试规则“功能进行了测试，以 `DOMAIN-SUFFIX,.0-000.store,Reject` 这条规则为例，此时 `.0-000.store` 和 `www..0-000.store`都正常被 REJECT 了，但 `www.0-000.store` 则是执行 FINAL 规则走的代理，并没有被拦截。因此，我认为是不是该规则在书写时多写了最前面的那个点，进而导致广告拦截失败。
我随后又去看了看 `Shadowrocket-ADBlock-Rules` 项目中是怎样的，发现在那个项目中，类似规则都是没有带点的（比如 adblock rules 规则），如下图所示。我认为这进一步地验证了我的看法。
![image](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/54212380/dc504087-4363-483f-8192-4a3c8d198d9d)
麻烦大佬看看我的看法是否正确。
由于我刚接触小火箭规则的编写，如有错误或打扰请见谅（*＾-＾*）

**Comment by Johnshall** [comment]
这个可能是因为上游规则出现了一些改版造成的，谢谢你的提醒，现在已经修复。
你的issue超酷的😎
