### ISSUE TITLE
希望添加百度贴吧APP，kds宽带山APP，水木社区APP，虎扑APP，开屏广告，谢谢！

### ISSUE THREAD

**Issue by AAfish** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#180]
可以出个教程iOS怎么抓开屏广告吗，这样大家一起搜集跟新可以。哈哈哈哈哈不知道是不是杯水车薪。

**Comment by Johnshall** [comment]
在数据->日志->代理中启动日志记录，然后迅速打开APP，然后在日志记录中搜寻开屏广告的链接。然后把它链接加入Reject中，看能否去除。
不过这种广告一般都有缓存，即使链接被ban了可能仍然会显示。
抱歉我不是很有精力去完成这件事。
