### ISSUE TITLE
希望能支持添加模块选项与自动更新快捷指令

### ISSUE THREAD

**Issue by UdyrLee** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#191]
首先谢谢大佬的苦心维护，在配置端更新，会造成常用的tiktok规则失效。（萌新没找到缘故）
希望能提供 模块更新的选项，其实原规则是可以直接添加到模块的，但显示是乱码，用倒是也能用的。但这样无法实现自动更新了，有找到其他去广告规则，它已实现了模块化与自动更新，但好像去广告效果没这个好用。希望能在百忙之中更新支持一下～ 谢谢

**Comment by Johnshall** [comment]
你好！谢谢你的issue！
因为我不用tiktok，所以也不会维护相关的tiktok规则。如果有兴趣可以试着来维护。
模块可以在配置->模块里添加。但我没找到 shadowrocket 提供更新模块的 url scheme。
