### ISSUE TITLE
微博去广告模块似乎有个bug？

### ISSUE THREAD

**Issue by 2583538** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#192]
搜索shadowrocket模块的时候找到这里，很感谢作者提供的模块，极大地满足了我的需求，再此感谢！

一个好像是bug的问题，微博去广告模块，如果没登录的话，并且开启插件，好像是无法登陆的，只有先关闭插件，在登陆，在开启插件才可以。

另外就是想求一个小红书去开屏广告的模块。

**Comment by Johnshall** [comment]
你好！谢谢你的issue！
本仓库没有维护微博去广告模块，你可以将issue投放到相应的仓库。
因为我太忙了，确实无力去完成某个特定app的去广告模块。
