### ISSUE TITLE
所有广告无效

### ISSUE THREAD

**Issue by xdtxAM** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#196]
能提供一下具体如何使用吗？
我在「Shadowrocket」首页最上面打开开关没然后，全剧路由设置「配置」，下面选项卡「配置」选择下载的配置文件，但是所有的开屏广告都在。

**Comment by xdtxAM** [comment]
> 能提供一下具体如何使用吗？ 我在「Shadowrocket」首页最上面打开开关没然后，全剧路由设置「配置」，下面选项卡「配置」选择下载的配置文件，但是所有的开屏广告都在。

https://siriusq.top/iOS%E5%B1%8F%E8%94%BD%E5%BC%80%E5%B1%8F%E5%B9%BF%E5%91%8A.html
找到了。但是感觉效果很一般

**Comment by Johnshall** [comment]
要想完全去掉广告需要HTTPS解密+抓包，维护成本有些大。很抱歉没有非常好的效果。
