### ISSUE TITLE
提个建议啊，能不能把ADGuard的规则集成进来，这样广告屏蔽的更多

### ISSUE THREAD

**Issue by lifestar2008** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#198]
如题，像爱奇艺的各种广告，包括暂停广告等，是不是能集成进来，不想来回切换App。
这是AdGuard的规则
https://[raw.nuaa.cf/217heidai/adblockfilters/main/rules/adblockdns.txt](https://raw.nuaa.cf/217heidai/adblockfilters/main/rules/adblockdns.txt)

**Comment by Johnshall** [comment]
已经包含ADGuard这个规则。但是因为HTTPS解密没有打开，所以效果有限。
这个网站屏蔽了很多ISP网段。
