### ISSUE TITLE
定制化的规则，fork后每天自动更新后就消失

### ISSUE THREAD

**Issue by MetaMee** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#201]
请问如何既能每天更新规则，又能保留自己的自定义规则呢？

**Comment by Johnshall** [comment]
把本项目提供的规则作为自定义规则的拓展配置

**Comment by Linlei-dev** [comment]
> 把本项目提供的规则作为自定义规则的拓展配置

请问是在小火箭本项目的配置上长按点击扩展配置，然后在扩展配置里面加上自定义的规则就可以了吗
