### ISSUE TITLE
现时点的广告过滤规则无法跳过bilibili的开屏广告

### ISSUE THREAD

**Issue by ChuBL** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#204]
规则更新时间10/23 2023
Bilibili版本：iOS 7.46.0
采用规则：直连去广告（https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_direct_banad.conf）

**Comment by 939243423** [comment]
还有闲鱼豆瓣 同去不掉

**Comment by ChongmingBird** [comment]
bilibili 开屏广告 最好还是去美区下载国际版app，非常精简，app内置的广告功能（会员购）也没有
