### ISSUE TITLE
lazy_group和lazy里面为什么个别分流规则是QuantumultX？

### ISSUE THREAD

**Issue by Brian2Z** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#206]
如下：
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list,苹果服务
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list,DIRECT

QuantumultX的匹配关键字是HOST-SUFFIX，在shadowrocket里面没法生效，是否有误？

**Comment by jiaoting** [comment]
的确是这样的

**Comment by jiaoting** [comment]
![IMG_EC3A019BEA45-1](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/12553424/cf8c177b-3bd1-4d23-8897-bceef853e26b)
![截屏 2023-11-09 20 03 55](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/12553424/aca25cca-2b53-493a-ac5b-6215a96ec775)

**Comment by Brian2Z** [comment]
> ![IMG_EC3A019BEA45-1](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/12553424/cf8c177b-3bd1-4d23-8897-bceef853e26b)
> 
> ![截屏 2023-11-09 20 03 55](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/12553424/aca25cca-2b53-493a-ac5b-6215a96ec775)
> 
> 

我可以确认这样是错误的，实际使用的时候不能正确的将微信分流到我指定的proxy，我将Quantumx改为Shadowrocket后就OK了

**Comment by Brian2Z** [comment]
Sorry，是我的问题。之前用小火煎版本比较老，升级到最新版之后，用QuantumultX的规则是兼容的。而且发现了为什么这几条要用Quan的规则 ，因为Quan的规则文件比小火煎完善得多。比如Apple.list那个，Quan的规则文件有几百条，而小火箭文件只有几条
