### ISSUE TITLE
lazy_group和lazy里面个别分流规则失效

### ISSUE THREAD

**Issue by jiaoting** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#212]
![](https://user-images.githubusercontent.com/12553424/281724720-cf8c177b-3bd1-4d23-8897-bceef853e26b.jpeg)

![](https://user-images.githubusercontent.com/12553424/281724728-aca25cca-2b53-493a-ac5b-6215a96ec775.jpeg)
需要将Quantumx改为Shadowrocket

**Comment by jiaoting** [comment]
修复了分流地址规则的笔误（Shadowrocket的规则误写为QuantumultX的规则）

**Comment by Brian2Z** [comment]
> 修复了分流地址规则的笔误（Shadowrocket的规则误写为QuantumultX的规则）

Sorry，是我的问题。之前用小火煎版本比较老，升级到最新版之后，用QuantumultX的规则是兼容的。而且发现了为什么这几条要用Quan的规则 ，因为Quan的规则文件比小火煎完善得多

**Comment by Brian2Z** [comment]
比如Apple.list那个，Quan的规则文件有几百条，而小火箭文件只有几条
