### ISSUE TITLE
請問能在跳過代理里加上Apple.com嗎，不加的話我翻譯和Apple Music無法加載出來

### ISSUE THREAD

**Issue by EKIKOUKA** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#222]

**Comment by leezhian** [comment]
safari 的翻译我有pr了，music 没在用，不清楚情况

**Comment by EKIKOUKA** [comment]
現在用不上了，沒法更新了，我自己加了不少reject規則，只把我常用的那幾個app里非必需的請求都攔截了，非必要不請求iPhoneから送信R5/12/07 17:36、Lee Zhi An ***@***.***>のメール:﻿
safari 的翻译我有pr了，music 没在用，不清楚情况
