### ISSUE TITLE
中国农业银行APP在规则下不能使用

### ISSUE THREAD

**Issue by Lion066** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#230]
使用规则：黑名单+去广告，白名单+去广告
中国农业银行APP检测到您网络存在风险，其他银行类APP也有类似情况，需要把这些APP跳过代理

![IMG_8128](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/97778001/8c3312f5-340a-4fd5-a289-422e8d924dda)

**Comment by Johnshall** [comment]
这是小火箭自己的问题，可以试着用跳过代理或者暂时关闭代理解决。

**Comment by Lion066** [comment]
> 这是小火箭自己的问题，可以试着用跳过代理或者暂时关闭代理解决。

使用小火箭默认的规则可以把一些网站手动加入“通用-跳过代理”列表，不知道订阅规则能不能做到这个
