### ISSUE TITLE
回国规则+去广告问题反应

### ISSUE THREAD

**Issue by ai63190079** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#231]
首先很感谢大佬的用心维护和无私的奉献。
海外用户添加此规则后，bilibili无法打开。ip111也无法开启。咸鱼和微信的小程序也无法刷新，等等问题。
麻烦大佬能够跟进下。谢谢。

**Comment by Johnshall** [comment]
抱歉我没有测试环境。你可以提供更全面的资料吗？
