### ISSUE TITLE
转区后的微信登陆后会被识别为不确定的网站而走代理

### ISSUE THREAD

**Issue by zhaom003** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#253]
本人微信电话号码变更为gv，使用白名单规则，在一次机场炸了之后发现微信不能联网，其他国内应用正常，关闭vpn后正常，后怀疑走了代理、后使用未转区微信以及黑名单测试，确定了转区后的微信登陆走的网址是阁下不确定的网站，而同样app登陆国内手机号的是国内直连

所以请将转区微信的链接网站加入到白名单中

**Comment by jyxjjj** [comment]
转区以后我看连的是SGWECHAT域名，我用[国内外划分 + 去广告]的情况下发现是直连的，然后手动加了走新加坡节点的规则，比正常只快了一点点一点点，故觉得加不加无所谓。不能连的问题可能是你IP被禁用？
