### ISSUE TITLE
中国区可以上tiktok了，但是配置文件下连不上

### ISSUE THREAD

**Issue by huxian02** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#256]
需要改成全代理才能连上tiktok。
配置文件是blacklist 不去广告版本

**Comment by DwyaneLee** [comment]
你好，你说的blacklist不去广告版本是这个吗？

**Comment by DwyaneLee** [comment]
你好，你说的blacklist不去广告版本是这个吗？
https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_banlist.conf    黑名单过滤

**Comment by huxian02** [comment]
完了，这下怎么连都上不去了，好像bug被字节修复了，算了

**Comment by DwyaneLee** [comment]
我还说怎么我换来换去都不行，用懒人那个也不行。。。我还以为我的节点问题
