### ISSUE TITLE
捷径如何填写规则文件地址？

### ISSUE THREAD

**Issue by wantaiyu** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#257]
不是很懂捷径打开后创建一个新的指令是如何把地址放进去，自动化倒是知道怎么操作。

**Comment by sourcelyee** [comment]
你先复制好你选择的规则地址，然后点击步骤一里的“路径”会自动跳转到快捷指令，然后替换里面的地址就好了。

**Comment by wantaiyu** [comment]
> 你先复制好你选择的规则地址，然后点击步骤一里的“路径”就会自动跳转到快捷指令，然后替换里面的地址就好了。

原来如此简单，感谢。之前我一直是复制规则地址，然后去快捷指令新建。
