### ISSUE TITLE
国内外划分规则领英国际版 app 不能用

### ISSUE THREAD

**Issue by misakaok** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#263]
需要手动添加规则 linkedin.com 代理才行 看了下配置文件内的规则是 # Linkedin
DOMAIN-SUFFIX,linkedin.cn,Proxy 

app 没法用 希望作者改成 # Linkedin
DOMAIN-SUFFIX,linkedin.com,Proxy

另外 bing 和 copilot 没问题

**Comment by cheneyxx** [comment]
# Linkedin
DOMAIN-SUFFIX,linkedin.cn,Proxy
DOMAIN-SUFFIX,linkedin.com,Proxy

**Comment by misakaok** [comment]
![image](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/10344793/ed990d80-4813-49da-8d3a-7ec844eae401)

**Comment by misakaok** [comment]
![image](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/10344793/8b691346-9a6d-4149-ba16-f9872d1778cf)
