### ISSUE TITLE
对于White List规则，bing.com应该过代理而不是直联

### ISSUE THREAD

**Issue by MIDE-589** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#268]
因为New Bing/Copilot的关系，bing.com应该走代理，而不是直联，这一点我在sr_top500_whitelist_ad.conf配置里看到了这样的一条配置：
# New Bing
DOMAIN-SUFFIX,bing.com,Proxy
想必是已经考虑了这一点。

但同时我在文件里又看到了这个配置
DOMAIN-SUFFIX,bing.com,Direct
感觉是冲突的，删掉后，能正常使用Copilot

p.s. 新年快乐

**Comment by QinZhaoXue** [comment]
是的，最近发现白名单规则一直用不了copilot，搞了好久microsoft的域名发现还是不能用，用sr_cnip可以但是这样会阻断apple apk域名的正常连接，导致原生的地图app以及相册app不能刷出来精确的定位图像信息，把bing.com的DIRECT规则去掉，只留下PROXY规则就可以完美使用地图和copilot了！！！nice

PS：新年快乐&元宵节快乐，身体健康以及万事如意

**Comment by lljbash** [comment]
@MIDE-589 @QinZhaoXue 
我提交了 pr 修复，两位可以在我的 fork 上验证一下。

不知作者@Johnshall 是否还活跃。

**Comment by Johnshall** [comment]
感谢修复！
抱歉实在太忙了，照顾不到这个项目了。感谢各位朋友能够帮助一起完善这个规则！
祝各位和家人身体健康，万事胜意！
