### ISSUE TITLE
Youtube APP的去广告最近不行了

### ISSUE THREAD

**Issue by liusmiler323** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#276]
最近不行了，把小火箭重新安装也不行。怎么办呀？

注意，是Youtube APP，不是手机浏览器网页版！

**Comment by iyuki0430** [comment]
建议装个uYouPlus版本的youtube app

**Comment by helpken** [comment]
> 最近不行了，把小火箭重新安装也不行。怎么办呀？
> 
> 
> 
> 注意，是Youtube APP，不是手机浏览器网页版！

我今天刚刚使用成功了   是用订阅才可以  我使用节点链接不行  我使用的是懒人的那个   我那个订阅是免费wireguard的订阅   在小火箭上添加了 本身订阅很慢 等他加载的时间广告都加载完毕了  我也看视频搭建过几个  自己感觉挺快但是链接上并不能去除广告
