### ISSUE TITLE
WeChat I18N (instead of Weixin) Domain Suffix Support

### ISSUE THREAD

**Issue by jyxjjj** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#280]
I am using United States Endpoints to reduce the probability of being banned by Google.

When downloading and uploading any wechat data (including chat messages, channels, chat videos and so on.), proxy will go to final to my proxy of United States Endpoints.

I really hope it can auto redirect to Singapore, but I know the configuration files will not know which/what is the endpoint's name of Singapore Endpoints.

So I tested the DIRECT Rule, and found it can successfully connected to wechat I18N, Please add support to let wechat connect to server directly.

**Comment by Johnshall** [comment]
Please have a try on this:
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever?tab=readme-ov-file#%E6%87%92%E4%BA%BA%E9%85%8D%E7%BD%AE-%E5%90%AB%E7%AD%96%E7%95%A5%E7%BB%84

**Comment by xinxinenjoy** [comment]
请教下这个懒人规则会不会面临这样一个问题？
不太明白分类列表里的域名是什么时间读取？是使用的时候再读列表→加载规则→生效。还是下载好配置文件的那一刻就已经加载内部所有的数据了？
