### ISSUE TITLE
仅去广告规则怎么配合其它规则联用？

### ISSUE THREAD

**Issue by ZtongChin** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#284]
首先！作为小火箭的用户很开心有这么好的作者来开发和维护这些规则配置，我只要是不明白“仅去广告规则”怎么配合其它规则使用？是直接更新下载在“模块”里吗？还是在“通用”下的“规则”中添加？或者直接添加配置文件？期待您的回复或者说明！

**Comment by XiangwanGuan** [comment]
使用去广告规则，然后在配置-通用-包含配置，选择懒人规则等配置，即可。

**Comment by xiaoaozhangfu** [comment]
> 使用去广告规则，然后在配置-通用-包含配置，选择懒人规则等配置，即可。

感谢，我终于学会了怎么做，你的方法是正确的，有效的
