### ISSUE TITLE
自动更新配置和一些其他小问题

### ISSUE THREAD

**Issue by EmryTardit** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#287]
首先谢谢大佬每日更新配置
只是没有找到快捷指令中自动化里的更新配置
![ED4CC213-AADB-4A57-880C-B3836D6C0365](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/153298960/87621522-e09b-4e6a-998c-2a75619eb912)
还有就是我发现知乎、携程等一些软件的开屏广告并没有被屏蔽，是正常的吗？我想知道是否可以自己找到这些软件开屏广告的链接来自己编辑配置文件呢？我不知道从哪里获取这些开屏广告的链接想请教一下。小白说错了请见谅

**Comment by Johnshall** [comment]
1. 关于如何自动更新，请参考：https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0

2. 关于一些软件的开屏广告并没有被屏蔽，可能是广告链接没有被加入到规则。

3. “我想知道是否可以自己找到这些软件开屏广告的链接来自己编辑配置文件呢？” 当然可以。

4. 关于如何找到广告链接，你可以在数据 -> 日志 -> 启动日志记录，开启日志记录后，自行判定哪些链接是广告链接。
