### ISSUE TITLE
希望将apple地图的api改成高德的

### ISSUE THREAD

**Issue by Gh-mean** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#29]
测试sr_top500_banlist规则和sr_cnip规则后发现apple地图依旧为国外地图供应商
希望将apple地图的域名及ip更新为直连而非代理

**Comment by Johnshall** [comment]
这是个上游的问题 
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/blob/master/factory/resultant/gfw.list#L17394
目前手动删除 DOMAIN-SUFFIX,apple.com,PROXY 这一行即可
如果这个问题持续时间长，我会进行手动干预

**Comment by Johnshall** [comment]
或者简单的使用白名单规则即可

**Comment by Gh-mean** [comment]
嗯，我已经通过将*.apple.com设置为direct解决了，就是之后不能自动更新了

**Comment by Johnshall** [comment]
过一段时间上游应该就修复了

**Comment by Johnshall** [comment]
Fixed https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/da957e0b4fc1d3f584a0ef8290ad73884ba420de
