### ISSUE TITLE
将linkedin.com添加到代理地址

### ISSUE THREAD

**Issue by SaHuyang77** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#291]
目前在使用whitelist_ad.conf
每次更新后都需要手动添加linkedin.com，以实现linkedin APP的访问，因为目前linkedin.cn已经完全成为一个企业服务招聘网站。需要访问linkedin只能代理。
申请将以下增加到代理清单
类型：DOMAIN-SUFFIX
策略：PROXY
域名：linkedIn.com

**Comment by HappyRespawnanchor** [comment]
你可以通过模块功能达成每次更新规则自动修改的效果，里面这样写即可：
```

#!name=名称

[Rule]
DOMAIN-SUFFIX,linkedIn.com,PROXY
```

**Comment by Johnshall** [comment]
抱歉，这个问题应该早一些修复。
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/2f011bfb9e5e007501451adecf22ad3acb254ac3
