### ISSUE TITLE
使用<黑名单+广告>规则无法购买apple gift card

### ISSUE THREAD

**Issue by ahillgian** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#30]
使用标题中的规则时, 在apple官网购买gift card可以添加到购物袋, 但点击购物袋中的 check out后 apple官网跳转到 page not found页面, 此时点击所有的apple页面都是 page not found. 关闭浏览器重新打开apple官网恢复正常, 但进入购物袋后check out以上问题重现.

经过测试, 不使用代理或者使用小火箭自带的默认规则可以正常购买gift card. 从而怀疑是 本项目中的某条规则导致的.

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/issues/29#issuecomment-1200352917
这是个上游的错误
可以使用白名单规则或者将*.apple.com设置为直连

**Comment by Johnshall** [comment]
Fixed https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/da957e0b4fc1d3f584a0ef8290ad73884ba420de
