### ISSUE TITLE
白名单+去广告模式下 LinkedIn错误

### ISSUE THREAD

**Issue by quan9364** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#300]
白名单+去广告模式下，Linkedin.com 应该是Proxy，但是该配置文件实际执行的是直连模式，导致无法访问境外Linkedin。目前的配置文件只有Linkedin.cn使用的是Proxy模式（但是这个没用，跳转的是CN广告页）。
因此建议将配置文件的Linkedin.com 修改为代理模式

**Comment by Johnshall** [comment]
Thanks!
