### ISSUE TITLE
怎么样可以连上tiktok和chatgpt呢

### ISSUE THREAD

**Issue by ks-zc** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#307]
chatgpt说我使用了vpn，不让用vpn访问
tiktok说网络连接不稳定
我是用的付费的

**Comment by ks-zc** [comment]
对了，我是ios手机，电脑没问题

**Comment by chux1995** [comment]
TikTok会检测系统语言和地区，之前甚至还会检查你的sim卡区号。

chatgpt我用客户端没问题。

**Comment by Johnshall** [comment]
ChatGPT能否使用取决于vps的IP，可以换个节点再试一下。
