### ISSUE TITLE
ios 地图app 白名单top500规则下无法规划路径

### ISSUE THREAD

**Issue by gemini-ae** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#308]
某些节点下开启白名单规则后使用地图app，当试图规划路径时，不管是公交还是步行还是其他都会提示不可用，猜测应该是对应的域名没有加入到白名单里面，导致走的是代理路线，关了代理就正常了。希望能修一修，非常感谢。

**Comment by XiangwanGuan** [comment]
可以用我的规则看看
