### ISSUE TITLE
QQ 图片加载不出来

### ISSUE THREAD

**Issue by AzuMiWanHua** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#31]
国内外划分的规则 QQ图片经常加载不出来 一直转圈 全局代理/直连都无问题

**Comment by AzuMiWanHua** [comment]
![3B6B5E1F-E497-4984-B9C8-885C1D487546](https://user-images.githubusercontent.com/87432333/183082257-6d2d42f7-5219-4fbd-9aac-3005541560d5.png)
![9A459490-F7B4-4F09-B2D1-7D77B8F86A3E](https://user-images.githubusercontent.com/87432333/183082270-446f6677-4257-404f-8e20-7bee0c4d7c95.jpeg)
图片一直转圈


> 国内外划分的规则 QQ图片经常加载不出来 一直转圈 全局代理/直连都无问题

**Comment by Johnshall** [comment]
规则没有问题，可能是你的网络环境不支持 ipv6 造成的。
请在配置中点击规则旁的ℹ️，通用，关闭“启动ipv6”选项试试。

**Comment by AzuMiWanHua** [comment]
> 规则没有问题，可能是你的网络环境不支持 ipv6 造成的。
> 请在配置中点击规则旁的ℹ️，通用，关闭“启动ipv6”选项试试。

试过了问题依旧存在
但是用黑名单那个规则就没有这个问题

**Comment by Johnshall** [comment]
你看看是否还有别的QQ相关地址走了proxy？

**Comment by AzuMiWanHua** [comment]
> 你看看是否还有别的QQ相关地址走了proxy？

![453AC1FB-FAEC-4829-9687-90094E28E455](https://user-images.githubusercontent.com/87432333/183089774-cd677b07-8274-49e5-86d9-a6026a06c6fc.png)
![3104E524-B606-4D50-895F-05D00B06D776](https://user-images.githubusercontent.com/87432333/183089783-c4766ed9-a191-4c04-9b91-817d0af18425.png)
但是全部代理的情况下 QQ图片也可以正常加载

**Comment by Johnshall** [comment]
我用了 sr_cnip.conf、sr_cnip_ad.conf 都没有复现这个问题。
可以试着更新一下规则和shadowrocket。

**Comment by AzuMiWanHua** [comment]
> 我用了 sr_cnip.conf、sr_cnip_ad.conf 都没有复现这个问题。
> 可以试着更新一下规则和shadowrocket。

都更新了的 你试一下流量情况下？ 我这好像是只有流量才会出现这种情况 WiFi没问题

**Comment by Johnshall** [comment]
抱歉，我还是没有复现这个问题。

**Comment by Johnshall** [comment]
如果有更新的情况，请放心的开启本issue。

**Comment by AzuMiWanHua** [comment]
> 如果有更新的情况，请放心的开启本issue。

今日删除app重新安装后问题解决 看来还是重装大法好用

**Comment by Johnshall** [comment]
有趣
