### ISSUE TITLE
配置后无法上google 试过提到的所有方法

### ISSUE THREAD

**Issue by lxo3o3** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#317]
老哥 我的配置如下不知道为啥上不了网 无法访问网页以及app
![IMG_0003](https://github.com/user-attachments/assets/2cddae59-6773-4242-854c-adfede901bbb)
![IMG_0004](https://github.com/user-attachments/assets/b2c32b3e-4044-4f3c-a7c7-859b9e9a8ecd)
![IMG_0005](https://github.com/user-attachments/assets/6122cb67-d4a2-407b-8e1a-e495f383df03)
![IMG_0006](https://github.com/user-attachments/assets/804451b1-c96a-4da9-a513-67fad7bbca07)

**Comment by Johnshall** [comment]
你设置为全局代理实际上规则已经不起作用了。应该是节点的问题。
