### ISSUE TITLE
关于自动更新配置文件

### ISSUE THREAD

**Issue by shuman77** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#320]
博主您好，因为我是第一次使用配置所以想请教一下您.我发一下我按照步骤设置的快捷指令，您帮我看看是否正确.
![IMG_4677](https://github.com/user-attachments/assets/e0bad0d8-ec93-4b03-bad5-5776326e87af)
![IMG_4678](https://github.com/user-attachments/assets/2800b119-3c48-45bd-85ce-572baaffcf24)
还有一个问题就是，我可不可以在文本里添加多个配置文件，可以让我这几个配置文件能同时更新，还是说如果我想做到这些，需要再去添加另外的快捷指令呢？麻烦您看到了可以回复一下，谢谢！！

**Comment by Johnshall** [comment]
配置应该是正确的。
如果需要实现多个规则更新，可以重复创建这个快捷指令，然后按照相同的设置步骤定时更新。但同时只有一个配置生效，你可以把每一个规则作为子规则添加到一个总的规则里。

**Comment by fay000fay** [comment]
> 配置应该是正确的。 如果需要实现多个规则更新，可以重复创建这个快捷指令，然后按照相同的设置步骤定时更新。但同时只有一个配置生效，你可以把每一个规则作为子规则添加到一个总的规则里。

我也是第一次用，我有个疑问，每次更新后，之前设置的分流策略就会被覆盖，要重新再手动操作一次，这就有点难受。比如 CHATGPT，YOUTUBE 这些策略，我设置了不同的节点。但更新就又被重置掉了。

**Comment by peep1221** [comment]
> > 配置应该是正确的。如果需要实现多个规则更新，可以重复创建这个快捷指令，然后按照相同的设置步骤定时更新。但同时只有一个配置生效，你可以把每一个规则作为子规则添加到一个总的规则里。
> 
> 我也是第一次用，我有个疑问，每次更新后，之前设置的分流策略就会被覆盖，要重新再手动操作一次，这就有点难受。比如 CHATGPT，YOUTUBE 这些策略，我设置了不同的节点。但更新就又被重置掉了。

是的，设置好的代理分组每次更新都会被清空，如果自动更新可以不影响这些自定义设置就好了
