### ISSUE TITLE
Student 

### ISSUE THREAD

**Issue by cclrc-01** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#321]
我这两天在小火箭里使用回国规则，发现好像效果不好，比如用酷狗音乐时，说我在不国内，后来我查了一下自己的IP地址，(在打开小火箭VPN 的情况下)，发现自己的IP地址还是在美国的，这不知道怎么回事? 希望能改进，能让我们真正回国，谢谢。还有广告屏蔽问题，只要使用这规则，比如在news popyard space 里查看新闻，立刻就出现弹框，上面显示出在使用广告拦截器，不能正常观看，但是使用懒人规则时一般不会类似弹框。

**Comment by Johnshall** [comment]
懒人规则不包含去广告，当然不会有类似的弹窗。
查ip地址的网站和部分软件可能不包含在回国规则里，抱歉我不是很有时间将它们都整理出来，还请见谅。你可以试着提出哪些网站需要加入在回国规则中。

**Comment by cclrc-01** [comment]
谢谢你，我只是希望能有所改善。

**Comment by cclrc-01** [comment]
懒人规则也有一定的去广告功能，有些广告能去，有些不能，但是我发现youtube的广告似乎很难去掉，即便用上广告规则。

**Comment by cclrc-01** [comment]
懒人配置-含策略组
不折腾，开箱即用。下载规则后可在 i -> 代理分组 中自行配置。

配置简洁
规则覆盖范围广
国内外常用app单独分流
添加自动切换延迟最低节点类型
通过「代理分组」灵活调整流媒体分流策略
规则地址：https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/lazy_group.conf

**Comment by cclrc-01** [comment]
再次感谢你的帮助和努力
