### ISSUE TITLE
希望可以加上youtube去广告，谢谢大佬

### ISSUE THREAD

**Issue by TangJianM** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#33]
萌新一只，请大佬指导一下

**Comment by TangJianM** [comment]
使用的是国内外区分➕去广告，然后youtube的广告无法去除

**Comment by Johnshall** [comment]
先开启HTTPS解密，然后在配置—>模块—>右上角+号—>从 https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Module/Block/YouTubeAds.sgmodule 下载去广告模块
