### ISSUE TITLE
苹果地图被屏蔽了

### ISSUE THREAD

**Issue by ioudove** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#334]
我使用的最新的规则，在我开启Shadowrocket的时候苹果地图无法联网，但是当我关闭了Shadowrocket，苹果地图立马就可以联网了

**Comment by cccyr999** [comment]
能联网，应该走的代理，不是直连。不能看交通实况。关掉梯子之后就能看交通实况

**Comment by Johnshall** [comment]
抱歉一直在忙。
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/155e675cd2fd4e58e246c7e7c4664748139217cb 希望这个可以解决问题。
