### ISSUE TITLE
URL Rewrite问题

### ISSUE THREAD

**Issue by Magi-xu** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#34]
[URL Rewrite]处 “\/\/” 导致safari无法跳转到google.com 改为 “//” 后正常

**Comment by Magi-xu** [comment]
<img width="217" alt="image" src="https://user-images.githubusercontent.com/56950761/184465699-50dfb0cb-41ee-4d58-aed9-abb7318f66aa.png">

**Comment by Johnshall** [comment]
> [URL Rewrite]处 “//” 导致safari无法跳转到google.com 改为 “//” 后正常

原谅我没有看懂。下面这个也和目前的写法相同。
在我的使用中，目前的 URL Rewrite 可以正常跳转 google.com，但是需要开启url解密。

**Comment by Magi-xu** [comment]
![0C42995E-11A5-40ED-90F6-15D02F9FC1F8](https://user-images.githubusercontent.com/56950761/184480385-b061f61d-8b5d-4bb8-bafa-9f50d488343e.png)因为规则在我这里下载下来后URL变成了这个样子，可能是什么地方出了问题，我把^https?:后面改成//就可以正常跳转了

**Comment by Johnshall** [comment]
您把 ^https?:\/\/(www.)?(g|google)\.cn 改成了 ^https?://(www.)?(g|google)\.cn ？是这个意思吗

**Comment by Magi-xu** [comment]
> 您把 ^https?:\/\/(www.)?(g|google)\.cn 改成了 ^https?://(www.)?(g|google)\.cn ？是这个意思吗

对对对

**Comment by Johnshall** [comment]
> ![0C42995E-11A5-40ED-90F6-15D02F9FC1F8](https://user-images.githubusercontent.com/56950761/184480385-b061f61d-8b5d-4bb8-bafa-9f50d488343e.png)因为规则在我这里下载下来后URL变成了这个样子，可能是什么地方出了问题，我把^https?:后面改成//就可以正常跳转了

反斜杠表示原有符号，这里不应该有问题。你的小火箭是最新版本吗

**Comment by Magi-xu** [comment]
> > ![0C42995E-11A5-40ED-90F6-15D02F9FC1F8](https://user-images.githubusercontent.com/56950761/184480385-b061f61d-8b5d-4bb8-bafa-9f50d488343e.png)因为规则在我这里下载下来后URL变成了这个样子，可能是什么地方出了问题，我把^https?:后面改成//就可以正常跳转了
> 
> 
> 
> 反斜杠表示原有符号，这里不应该有问题。你的小火箭是最新版本吗

是的，最新版本的小火箭。其实按照你的方法重新解密HTTPS也可以正常跳转，但是不加这两个反斜杠就能直接正常跳转。

**Comment by Johnshall** [comment]
奇怪，我把反斜杠去掉然后关闭https解谜无法正常跳转。是我没有理解到位嘛？

**Comment by Magi-xu** [comment]
> 奇怪，我把反斜杠去掉然后关闭https解谜无法正常跳转。是我没有理解到位嘛？

HTTPS解密是需要开的。只是我发现每次更新更新规则之后要关闭HTTPS解密再重新打开，而去掉反斜杠就不需要这样。

**Comment by Johnshall** [comment]
哇！太感谢了！终于解决了这个问题！

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/d6a39ceecb54179f2671989c0080ad4b6fcd139b
已解决，感谢反馈。

**Comment by Magi-xu** [comment]
> 哇！太感谢了！终于解决了这个问题！

哈哈，不客气。也感谢你做的一切！
