### ISSUE TITLE
关于苹果地图在使用配置文件时无法使用的情况

### ISSUE THREAD

**Issue by Moriaty911** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#343]
经测试，应在配置文件内加入
`DOMAIN-SUFFIX,gspe19-cn-ssl.ls.apple.com,DIRECT`
 即可解决问题

**Comment by Johnshall** [comment]
抱歉一直在忙。
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/155e675cd2fd4e58e246c7e7c4664748139217cb 请问是否修复了问题？

**Comment by Moriaty911** [comment]
谢谢。ios端经测试已经能够正常使用，调用数据为高德地图数据。然而mac端经测试默认调用的不是国内的高德地图数据，需手动将代理关闭并重启地图才能调用国内高德地图数据。目前我也在用surge抓包看具体是哪个api判断mac地图是否调用国内高德地图数据。

**Comment by Moriaty911** [comment]
经测试，应在配置文件->通用->跳过代理中添加
`*.ls.apple.com`
mac地图即可加载国内高德地图数据
![Screenshot 2024-10-03 at 11 23 27 AM](https://github.com/user-attachments/assets/5483c7ba-4777-4783-a93e-5448c812d2fc)

**Comment by Johnshall** [comment]
> 经测试，应在配置文件->通用->跳过代理中添加 `*.ls.apple.com` mac地图即可加载国内高德地图数据 ![Screenshot 2024-10-03 at 11 23 27 AM](https://private-user-images.githubusercontent.com/47228745/373103553-5483c7ba-4777-4783-a93e-5448c812d2fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MzMxMjgsIm5iZiI6MTcyNzkzMjgyOCwicGF0aCI6Ii80NzIyODc0NS8zNzMxMDM1NTMtNTQ4M2M3YmEtNDc3Ny00NzgzLWE5M2UtNTQ0OGM4MTJkMmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA1MjAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YzI4YjY3YjBhMTMzOTZmZGJhYjExYmZhZWZlYTQ0YjdmNDhlMWUwNzA1OTMyZGUzNzllMDk5ZWZiZmMwNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qPaP3oaDPXQ5NPdunFQpGUTqHDUeKmzwiRL4uaKL2-M)

https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/8e8d550a08bcdf87804175460b1897aafe217da2 已添加，麻烦进行测试。

**Comment by Moriaty911** [comment]
已测试，ios端及mac端地图目前已可以正常加载高德地图数据

**Comment by Moriaty911** [comment]
close

**Comment by Johnshall** [comment]
非常感谢您的贡献！
