### ISSUE TITLE
无法使用Bing引擎

### ISSUE THREAD

**Issue by Snan1128** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#35]
使用这个规则后Bing搜索一直处于加载状态

**Comment by Johnshall** [comment]
用的哪个规则？

**Comment by Snan1128** [comment]
第一个规则，即（黑名单＋去广告）

**Comment by Snan1128** [comment]
抱歉，这个问题可能是由Safari浏览器造成的，我刚刚开这个规则又试了几遍，bing可以访问了。

**Comment by Johnshall** [comment]
没事的，bing在国内常受到dns污染和神秘阻断，打不开很正常。
我会关闭这个issue。如果有补充可以开启。
