### ISSUE TITLE
DNS上游服务器

### ISSUE THREAD

**Issue by guren777** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#36]
你好，在配置文件已成功修改DNS上游服务器地址。但是不能执行！

# Shadowrocket: 2022-08-25 19:28:41
[General]
hijack-dns = 
include = BaiduAdBlock.conf
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, e.crashlytics.com, captive.apple.com
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server = https://dns.quad9.net/dns-query,https://dns.adguard-dns.com/dns-query,
update-url = https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_whitelist_ad.conf

[Rule]
#
# 白名单中包含了境外网站中可以访问的那些，对不确定的网站则尽可能地代理。
#
# 直连：top500 网站中可直连的境外网站、中国网站
# 代理：默认代理其余的所有境外网站
# 包含广告过滤

**Comment by Johnshall** [comment]
报什么错误呢？BaiduAdBlock.conf是否存在？

**Comment by guren777** [comment]
> 报什么错误呢？BaiduAdBlock.conf是否存在？

你好，没有报错。修改以后不生效。dns走的是运营商的。不是我设置的dns

**Comment by guren777** [comment]
DNS上游服务器 想替换成下面这两个

https://dns.adguard-dns.com/dns-query
https://dns.quad9.net/dns-query

**Comment by Johnshall** [comment]
BaiduAdBlock.conf 中有设置的dns服务器吗？是否冲突？

**Comment by guren777** [comment]
> BaiduAdBlock.conf 怎么定义dns服务的？会不会冲突？

你好，没有冲突。

# Shadowrocket: 2022-08-26 13:54:55
[General]
update-url = https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/Loon/Plugin/BaiduAdBlock.plugin

[Rule]
#百度输入法
DOMAIN-KEYWORD,jomodns,REJECT
DOMAIN,res.mi.baidu.com,REJECT
DOMAIN,r6.mo.baidu.com,REJECT

[URL Rewrite]
^https:\/\/dss0\.bdstatic\.com\/.+/tam-ogel\/.+\.jpg _ reject
https:\/\/pan\.baidu\.com\/pmall\/order\/privilege\/info _ reject
https:\/\/pan\.baidu\.com\/rest\/.+\/pcs\/adx _ reject
https:\/\/pan\.baidu\.com\/api\/useractivity\/activity _ reject
http:\/\/pan\.baidu\.com\/act\/.+\/bchannel\/list _ reject
https:\/\/pan\.baidu\.com\/component\/view\/1510\?from _ reject
https:\/\/sofire\.baidu\.com\/ios\/.+ _ reject
https:\/\/ndstatic\.cdn\.bcebos\.com\/activity\/welfare\/js\/.+\.js _ reject
https:\/\/ndstatic\.cdn\.bcebos\.com\/activity\/welfare\/index\.html _ reject
https:\/\/pan\.baidu\.com\/pmall\/order\/privilege\/info _ reject
https:\/\/staticsns\.cdn\.bcebos\.com\/amis\/.+/banner.png _ reject
http:\/\/rp\.hpplay\.cn\/logouts _ reject
https:\/\/issuecdn\.baidupcs\.com\/issue\/netdisk\/ts_ad\/ _ reject
https:\/\/pan\.baidu\.com\/rest\/2.0\/pcs\/adv\? _ reject
https:\/\/pan\.baidu\.com\/component\/view\/(1510|1130)\?vip _ reject
^https:\/\/mime\.baidu\.com\/v5\/activity\/advertisementnonrealtime _ reject
^https:\/\/mime\.baidu\.com\/v5\/start_screen_ads\/list _ reject
^https:\/\/mime\.baidu\.com\/v5\/hotpatch\/check\?hotpatch _ reject
^https?:\/\/c\.tieba\.baidu\.com\/c\/s\/splashSchedule _ reject
^https?:\/\/c\.tieba\.baidu\.com\/c\/f\/forum\/getAdInfo _ reject
^https?:\/\/c\.tieba\.baidu\.com\/\w+\/\w+\/(sync|newRnSync|mlog) _ reject
^https?:\/\/((25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\/\w+\/\w+\/(sync|newRnSync|mlog) _ reject
^https?:\/\/((25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\/c\/s\/splashSchedule _ reject

[MITM]
hostname = sofire.baidu.com,ndstatic.cdn.bcebos.com,pan.baidu.com,staticsns.cdn.bcebos.com,issuecdn.baidupcs.com,dss0.bdstatic.com,*.tieba.baidu.com
