### ISSUE TITLE
【求助】仅想去广告应该选“仅去广告”还是“直连去广告”

### ISSUE THREAD

**Issue by hl8686** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#360]
如题，就是日常考虑续航，都是有科学上网需求的时候才启动小火箭，然后又特别受不了ios开屏广告（安卓可以用李跳跳屏蔽大部分），想问下我这种需求选仅去广告还是直连去广告，如果选仅去广告，是只要在小火箭的“配置”选项里确定勾选了，不启动（就是首页那里显示未连接）也行，还是必须启动分流才能生效？

【其实就是没太明白仅去广告和直连去广告的区别，软件操作上的不同，以及哪个更无感、能耗更小】

非常感谢作者大大，期待回复

**Comment by JinjaNatsume** [comment]
仅去广告是搭配其他规则使用的，没有设定final走的流量，而直连会设定final走直连
