### ISSUE TITLE
关于PAC

### ISSUE THREAD

**Issue by l00jj** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#37]
大佬，我想把你的的conf做成PAC，我用的是 [SwitchyOmega] chrome的插件，里面PAC是js代码，我准备需要自己写一套转换代码，不过是否已经有大佬做了类似的东西可以直接用呢？

**Comment by Johnshall** [comment]
抱歉哈，我对 SwitchyOmega 不太感兴趣。
你可以用v2ray或者sing-box的路由功能实现分流。
例如 https://github.com/Johnshall/v2ray-rules-dat 将可以获得与本规则相当的去广告功能。
