### ISSUE TITLE
快捷指令中无[Shadowrocket 规则自动更新]

### ISSUE THREAD

**Issue by Caesar-Victory** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#374]
system version: 18.2
devices: iPhone 16 Pro Max
![c94afdc3338e23a3f3a7d9162c820fb6](https://github.com/user-attachments/assets/02312ecd-6c1c-4c05-90ad-72698f63f9b5)

**Comment by Johnshall** [comment]
看文档
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever?tab=readme-ov-file#如何自动更新
