### ISSUE TITLE
快捷指令中无法找到自动更新配置

### ISSUE THREAD

**Issue by NocturneJay** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#376]
![image](https://github.com/user-attachments/assets/ada42dae-21ee-44aa-8f8a-d76c5a2abf2d)如图
系统：ios18.1.1
设备：iphone 15pro

**Comment by Johnshall** [comment]
和 @Caesar-Victory 一起看文档 https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever?tab=readme-ov-file#如何自动更新
