### ISSUE TITLE
能不能把配置设置成默认打开脚本

### ISSUE THREAD

**Issue by c740030066** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#40]
1.能不能把配置默认启动脚本，每天都更新配置，就要每次都要重新打开一下脚本启动，很麻烦。

2.https解密打开好还是不打开好，我是使用你们的国内直连 + 国外代理 + 去广告。

**Comment by Johnshall** [comment]
1. [如何自动更新](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever#%E5%A6%82%E4%BD%95%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0)
2. 如果Safari可以正常跳转Google，不需要YouTube去广告脚本，可以关闭。

**Comment by c740030066** [comment]
你好，可否给个联系方式，有点不是很懂，想问问你

**Comment by Johnshall** [comment]
没有联系方式，实在抱歉
你可以在这里详细描述下可以吗

**Comment by dogefy** [comment]
脚本默认启用或许可以将enable字段false改为true，建议fork后自行修改定制

**Comment by c740030066** [comment]
但是我发现规则估计弄得不完整，有些还是没加载出来，作者看到希望帮忙处理一下，麻烦了，谢谢作者，估计就是没有走直连才会这样的！

**Comment by c740030066** [comment]
后面我删掉上面那条添加的规则，我自己添加
类型：DOMAIN-SUFFIX
策略：DIRECT
域名：cn
就可以了，但是我不知道这样会不会出现弊端，例如后面国内有些网址还是国外有些网址，不走直连或者不走代理，所以麻烦作者研究一下，顺便更新一下规则进去，我每天都更新你们的规则，作者要添加进去规则，不然我更新完又要手动自己填进去规则

**Comment by c740030066** [comment]
就证明，当时刷朋友圈走得是代理，导致的，麻烦作者优化一下，国内直连，有些没有走到直连

**Comment by c740030066** [comment]
我还发现tim应用也有这种情况，聊天有些图片刷不出来，后面直接关闭小火箭VPN，就可以刷出来了

**Comment by dogefy** [comment]
> 后面我删掉上面那条添加的规则，我自己添加
> 
> 类型：DOMAIN-SUFFIX
> 
> 策略：DIRECT
> 
> 域名：cn
> 
> 就可以了，但是我不知道这样会不会出现弊端，例如后面国内有些网址还是国外有些网址，不走直连或者不走代理，所以麻烦作者研究一下，顺便更新一下规则进去，我每天都更新你们的规则，作者要添加进去规则，不然我更新完又要手动自己填进去规则，作者看看要怎么弄，我怕我这条规则与作者你弄的规则会冲突，麻烦作者看看

这一条规则在whitelist相关配置文件中已经包含了，希望能提供一下错误走了代理的域名

**Comment by c740030066** [comment]
shmmsns.qpic.cn
貌似是这条 你看看

**Comment by Johnshall** [comment]
这个是因为 DNS 解析到国外去了，如果 DNS 正确解析到国内不会发生这个问题。

**Comment by Johnshall** [comment]
让我想想如何处理好这个问题

**Comment by c740030066** [comment]
好的，谢谢，麻烦作者了，辛苦了！

对哦，那个配置YouTube 去广告脚本 好像失效了 可否直接弄掉它吧，每次更新脚本还在

**Comment by Johnshall** [comment]
> 好的，谢谢，麻烦作者了，辛苦了！
> 
> 对哦，那个配置YouTube 去广告脚本 好像失效了 可否直接弄掉它吧，每次更新脚本还在


是的，但是它是默认关闭的。这个脚本对老版本 Youtube 还是有效的。

**Comment by c740030066** [comment]
http://shmmsns.qpic.cn/mmsns/20uffq6ObHXNHuvCrW5S3KZMD6L6UDjeODEkRwHLFUqhxR072Dvva2gNIRibhgnqKkzPNkOZggicM/0?tp=wxpc&length=1792&width=828&idx=1&token=WSEN6qDsKwV8A02w3onOGQYfxnkibdqSOkmHhZGNB4DEQENqZEibVegpAKMaDvlEOmLiaPm9UxDHvKySkTlK84bicA



http://shmmsns.qpic.cn/mmsns/20uffq6ObHXNHuvCrW5S3KZMD6L6UDjeODEkRwHLFUqhxR072Dvva2gNIRibhgnqKkzPNkOZggicM/0?tp=wxpc&length=1792&width=828&idx=1&token=WSEN6qDsKwV8A02w3onOGQYfxnkibdqSOkmHhZGNB4DEQENqZEibVegpAKMaDvlEOmLiaPm9UxDHvKySkTlK84bicA




刚看了一下 又走代理了 微信WeChat 朋友圈图片又一直加载 看不了 很头疼

**Comment by Johnshall** [comment]
你可以先用白名单规则。

**Comment by c740030066** [comment]
![A536CA54-D67E-4396-A396-B132296F74D7](https://user-images.githubusercontent.com/101859405/192545820-db1c3c2e-e880-4a62-85cb-3b5f7cb493bd.jpeg)

作者 ni kan kan

**Comment by Johnshall** [comment]
> ![A536CA54-D67E-4396-A396-B132296F74D7](https://user-images.githubusercontent.com/101859405/192545820-db1c3c2e-e880-4a62-85cb-3b5f7cb493bd.jpeg)
> 
> 作者 ni kan kan

这个不是白名单规则，白名单规则指明了 *.cn 走直连，你可以先用着。
国内外划分规则强依赖 DNS 服务器解析到的 ip 位置，而小火箭处理 DNS 的方式不太明确，我在想怎么处理。

**Comment by c740030066** [comment]
我想国内直连+国外代理的话，白名单会不会准确性更好，更高？

**Comment by c740030066** [comment]
我还发现http://szmmsns.qpic.cn/mmsns/SNib8eXrk1ETA9DuX4Myn4R5vJl2rXM99S5sX4WfVMeicpTT9yYVHhhrJGMpIRNib5vvP0CtA5UibFU/150?tp=wxpc&length=1792&width=828

域名szmmsns.qpic.cn

也走代理了

**Comment by c740030066** [comment]
![42272A49-6179-40EB-AE0F-903B4BFC3A47](https://user-images.githubusercontent.com/101859405/192554156-c1ec25f3-c1ba-4b6d-af26-2081122de962.png)
由于广州地铁会检测代理，我用了模块才不会显示弹窗，

https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/sgmodule/General.sgmodule

作者顺便帮我看看会不会与你的规则冲突什么的，需不需要优化一下这模块还是什么

**Comment by c740030066** [comment]
trade-acs.m.taobao.com:443
我发现这条 也走代理了

**Comment by Johnshall** [comment]
> 由于广州地铁会检测代理，我用了模块才不会显示弹窗，
> 
> https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/sgmodule/General.sgmodule
> 
> 作者顺便帮我看看会不会与你的规则冲突什么的，需不需要优化一下这模块还是什么

这个以后有时间看看吧，冲突应该不会的。

**Comment by Johnshall** [comment]
> trade-acs.m.taobao.com:443 我发现这条 也走代理了

你那里的DNS服务器怎么在乱解析，你把quic那个dns服务器去掉试试？

**Comment by c740030066** [comment]
好的 谢谢作者，我现在去掉，你也去掉一下，以免明天更新配置，又有

**Comment by Johnshall** [comment]
我需要更长的时间去测试，不一定会去掉。

关于 DNS 处理：
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/issues/22#issuecomment-1259606152

**Comment by Johnshall** [comment]
终究还是去掉了 iQDNS，确实G了
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/bc30baaa56fe31fb83c5c94952131d2c7c6bba0c

**Comment by c740030066** [comment]
好的，作者，记得更新规则去掉，顺便也去掉 规则 通用 启用IPv6 吧 听说这个功能也没什么用

**Comment by c740030066** [comment]
nisgd2.10010.com:38750
这条应该是联通的吧，也走代理了

**Comment by Johnshall** [comment]
国内 ipv6 经常出问题，确实可以去掉。
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/c0f05099dbefe45c4864308f16d301a8b1b1dba7

**Comment by Johnshall** [comment]
> nisgd2.10010.com:38750 这条应该是联通的吧，也走代理了

这些是你那里dns服务器的问题，不用单独报。更新规则+重启手机再看看有没有问题。

**Comment by c740030066** [comment]
对呀，作者 记得去掉 启动ipv6 跟去掉quic dns 这两个，我明天早上更新一下

**Comment by Johnshall** [comment]
国内外划分规则依据本地dns解析到的ip地理位置进行划分，如果本地dns解析ip不精确，最好使用黑名单或白名单。

**Comment by Johnshall** [comment]
根据反馈，本帖已完成，

**Comment by Johnshall** [comment]
根据反馈，本帖已完成。
