### ISSUE TITLE
easylistchina规则转换丢失

### ISSUE THREAD

**Issue by johnsonz** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#42]
看到代码里有`https://easylist-downloads.adblockplus.org/easylistchina.txt`链接规则，但是在生成的去广告规则里面确缺了一些，因为本人偶尔看小说，是广告的重灾区，比如广告`https://vlets.bust3koop.cyou/xling_3034_1_wqoxn.js?7834562561664377310097`在easylistchina里可以搜索到
![Screenshot 2022-09-28 231836](https://user-images.githubusercontent.com/2533629/192818493-f89db937-67fb-4ebe-b9f7-88056238add6.png)
但是在[黑名单规则 + 去广告](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/#%E9%BB%91%E5%90%8D%E5%8D%95%E8%BF%87%E6%BB%A4--%E5%B9%BF%E5%91%8A)里按照域名却搜索不到

**Comment by Johnshall** [comment]
本规则每天8点钟更新，而 easylist 的规则更新时间就不确定了。等一等就好。
