### ISSUE TITLE
YouTubeAds Block not working

### ISSUE THREAD

**Issue by austiecodes** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#44]
去广告部分自带的 YouTube 去广告脚本不可用。
我自己将其改成了来自神机的重写规则，测试后发现可用。建议删除去广告脚本（该脚本已过时）

```
[URL Rewrite]
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 header
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad - reject

^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v\d\/player\/ad_break - reject
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads - reject
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) - reject
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext - reject

[MITM]
hostname = %APPEND% -redirector*.googlevideo.com,*.googlevideo.com,www.youtube.com,s.youtube.com,youtubei.googleapis.com
```

**Comment by Johnshall** [comment]
已去除自带的 Youtube 去广告脚本
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/99c82669a9f4b273ba0a6c25e426e42f602dee31

**Comment by Johnshall** [comment]
YouTube 去广告脚本可靠性未知，且可能会引发一些问题。我没有精力和兴趣去维护这种类型的脚本。
可能更好的方法是在 配置 -> 模块 -> 点击右上角+号 -> 从给定的 URL 下载配置，使用以下链接
https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Module/Block/YouTubeAds.sgmodule

这样可以既不改变规则本身，又增加去广告的功能。

或者可以自行 fork 后加入上述内容。
由于本规则需要考虑普适性、稳定性（大部分用户可能不会及时更新规则，但会更新 YouTube 客户端），所以并不打算通过这样的方式直接嵌入。
