### ISSUE TITLE
please add tedcdn.com

### ISSUE THREAD

**Issue by Accelerator086** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#46]
`DOMAIN-SUFFIX,tedcdn.com,Proxy`

Ted app 在现有的规则下（direct）能够打开，规则里已经有这一条而且不需要改了：`DOMAIN-SUFFIX,ted.com,Direct`，但是加载视频非常慢。

我试着把这个域名 `DOMAIN-SUFFIX,tedcdn.com,Proxy` 加入规则后，视频就流畅且高清了。

**Comment by Johnshall** [comment]
Move Ted to proxy.
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/e1a03a751105393f2cb2ee3645ebfd7950e79dad

**Comment by Accelerator086** [comment]
> Move Ted to proxy. [e1a03a7](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/e1a03a751105393f2cb2ee3645ebfd7950e79dad)

Thank you and it works.
