### ISSUE TITLE
请问一下国内APP广告可以去吗

### ISSUE THREAD

**Issue by WangNian007** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#47]

**Comment by Johnshall** [comment]
Why not.

**Comment by WangNian007** [comment]
但是我用了之后发现例如wb，blibli这些的广告都还在

**Comment by Johnshall** [comment]
由于只能通过url过滤广告，为了性能也不宜开启 https 解密所有内容，因此去广告不一定完全，更多的去广告还是需要搭配脚本。详见https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/issues/6
