### ISSUE TITLE
关于ios捷径

### ISSUE THREAD

**Issue by Klaus-Kin** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#48]
如题
1.说明中是选择“打开快捷指令“，实测应该是运行快捷指令（此种情况下非锁屏界面能够完成目的）
2.为什么锁屏后出错？现实无法打开

**Comment by Klaus-Kin** [comment]
报错信息：
快捷指令
自动化失败
〝16:54，每天”遇到错误：“快捷指令”无法为
URL方案“shadowrocket”打开 App。它可能没有
安装在这台设备上

 设备信息ios16  ，13pm

**Comment by Klaus-Kin** [comment]
运行前询问也关掉了

**Comment by Johnshall** [comment]
在 Safari 地址栏输入：
shadowrocket://config/add/https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/release/sr_top500_whitelist.conf
会显示什么？

**Comment by Klaus-Kin** [comment]
> 在 Safari 地址栏输入：
> shadowrocket://config/add/https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/release/sr_top500_whitelist.conf
> 会显示什么？

正常导入规则到小火箭，

**Comment by Klaus-Kin** [comment]
> 在 Safari 地址栏输入：
> shadowrocket://config/add/https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/release/sr_top500_whitelist.conf
> 会显示什么？

而且我在网上查了，说好像就是不支持锁屏运行自动化.....您的是可以的吗？

**Comment by Johnshall** [comment]
> > 在 Safari 地址栏输入：
> > shadowrocket://config/add/https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/release/sr_top500_whitelist.conf
> > 会显示什么？
> 
> 而且我在网上查了，说好像就是不支持锁屏运行自动化.....您的是可以的吗？

这个都不行...

**Comment by Johnshall** [comment]
在快捷指令中手动激活更新脚本可以正常运行吗？

**Comment by Klaus-Kin** [comment]
> 在快捷指令中手动激活更新脚本可以正常运行吗？

可以的。矛盾点只在于，锁屏的时候就不能更新，比我我八点半才醒...八点在这之前都是锁屏，然后就不能运行（只能在解锁手机屏时候才能运行）

**Comment by Johnshall** [comment]
你可以设置它十点钟运行脚本啊...

**Comment by Klaus-Kin** [comment]
> 



> 你可以设置它十点钟运行脚本啊...

是的，但是他运行的前提是手机解锁，就是我不知道会在什么时候解锁手机....话说回来，如果这个是ios的限制，那应该没有办法...😔，我还以为是我哪里设置有问题了。
