### ISSUE TITLE
请求添加vox进入规则

### ISSUE THREAD

**Issue by meme996sayNO** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#5]
使用的规则是：黑名单+去广告
在打开vox时，日志显示：**FINAL,DIRECT**

**Comment by meme996sayNO** [comment]
另外，想请教一下在使用您的含“去广告”的小火箭规则时，是否需要打开https解密、生成新的证书呢？

**Comment by Johnshall** [comment]
> 使用的规则是：黑名单+去广告 在打开vox时，日志显示：**FINAL,DIRECT**

您好！
&ensp;首先感谢您的 issue，我想您提出的 vox 应该是指 vox.com。这是由于上游 [gfw list](https://github.com/gfwlist/gfwlist)，与 [Loyalsoldier/cn-blocked-domain](https://github.com/Loyalsoldier/cn-blocked-domain) 没有将 vox.com 加入到列表中。而黑名单+去广告规则仅仅依赖以上两个列表构建，所以无法正确的将 vox.com 解析为代理。本项目无法处理上游数据库错误，您可以通过手动将 vox.com 加入到代理的列表中来实现代理连接；

&ensp;另外，我通过 https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/8dad1d0f3f12e38e49a4936e6b784f51e11669e9 与 https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/eeef03cb91cca392bf6aabfa190b30f56095702d 将 vox.com 加入到 sr_top500_whitelist_ad.conf 和 sr_top500_whitelist.conf。您可以通过订阅上述两个文件来实现对 vox.com 实现代理。

**Comment by Johnshall** [comment]
> 另外，想请教一下在使用您的含“去广告”的小火箭规则时，是否需要打开https解密、生成新的证书呢？

是的，通过开启 https 解密可以通过中间人攻击的方式获取原始的请求头，实现对 https 流量广告的拦截。

如果我解决了您的问题，烦请您关闭此 issue，如果还有其他的问题，欢迎继续评论。
祝您新年快乐！
Johnshall 敬上
