### ISSUE TITLE
无法玩Start里的游戏

### ISSUE THREAD

**Issue by ikelvinwoo** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#50]
我有尝试白名单、黑名单、国内外划分。每个都加了过滤广告，请问为什么无法玩Start里的云游戏？我关了代理就可以玩了，之前用ClashX Pro也可以玩。我用的是M1的Macbook Pro，谢谢！

**Comment by Johnshall** [comment]
什么是 start？

**Comment by ikelvinwoo** [comment]
> 什么是 start？

Start云游戏，腾讯出品的一块云游戏软件。

参考链接：https://start.qq.com/

**Comment by Johnshall** [comment]
Start云游戏服务器在国内，无需用小火箭呀

**Comment by ikelvinwoo** [comment]
> Start云游戏服务器在国内，无需用小火箭呀

对的，但是玩的同时也想访问Google查询一些攻略嘛～

**Comment by Johnshall** [comment]
要不你翻翻 Shadowrocket 的日志？看看 Start 云游戏服务器是不是走了代理？我比较忙，只能说 pr welcome。
Shadowrocket 实现的时候很强调内存占用，导致性能并不是很好。云游戏挺烧带宽和延迟的，用小火箭估计游戏效果也不好。

**Comment by ikelvinwoo** [comment]
哦哦 原来是这样～ 好的谢谢～ 那您有什么推荐的软件吗？

**Comment by ikelvinwoo** [comment]
> 要不你翻翻 Shadowrocket 的日志？看看 Start 云游戏服务器是不是走了代理？我比较忙，只能说 pr welcome。 Shadowrocket 实现的时候很强调内存占用，导致性能并不是很好。云游戏挺烧带宽和延迟的，用小火箭估计游戏效果也不好。


哦哦 原来是这样～ 好的谢谢～ 那您有什么推荐的软件吗？

**Comment by Johnshall** [comment]
Clash、*ray、sing-box...
电脑上选择空间就很大了。

**Comment by ikelvinwoo** [comment]
> Clash、*ray、sing-box... 电脑上选择空间就很大了。

谢谢～～～

**Comment by Johnshall** [comment]
不谢～
