### ISSUE TITLE
小火箭里的远程文件

### ISSUE THREAD

**Issue by peacoock** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#52]
原来使用小火箭扫描h2y的二维码时，会有一个远程文件，然后每次rule更新，我会点击一下重新下载并覆盖就可以了；这里新的二维码扫描之后，是会直接下载一个配置，但是没有远程文件的链接，请问能做的和原来一样么？

**Comment by Johnshall** [comment]
这个二维码应该用 Safari 扫描。Shadowrocket 也可以，不过会重复下载。但是扫描二维码本来就是为了新添加规则而定的，也无伤大雅。
远程文件的链接在“规则地址”，直接复制也行。
更新配置只需要点一下规则名，然后选更新配置就行了，无需扫描二维码什么的。

**Comment by peacoock** [comment]
确实无伤大雅
通过解析两个二维码，比如白名单
h2y的是https://h2y.github.io/Shadowrocket-ADBlock-Rules/sr_top500_whitelist.conf
johnshall的是shadowrocket://config/add/https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_whitelist.conf
所以后面的可以用相机扫描，并会调动app而前面的不能，也算是解决了我的疑惑，谢谢✌️
