### ISSUE TITLE
自动更新方法使用快捷指令方法有一点点不是很准确

### ISSUE THREAD

**Issue by shankangk** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#53]
步骤二：打开“快捷指令”下方的“自动化”，轻击右上角加号，点击“创建个人自动化”，选择“特定时间”，设定时间为 8:05 或更晚的时间（规则生成需要一定时间），点击下一步，点击添加操作，选择 APP 栏，找到快捷指令，选择“**_打开快捷指令_**”，点击浅色“快捷指令”，选择“Shadowrocket 规则自动更新”，点击下一步，关闭运行前询问（可选），点击完成即可。

## "打开快捷指令"应该改为"运行快捷指令"，快捷指令这两个选项都存在
![IMG_4116](https://user-images.githubusercontent.com/45353276/201053836-0ac2282b-fea6-44f7-bc8a-f4c0b7968537.jpg)

**Comment by Johnshall** [comment]
已修改，感谢！
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/79067aa14f484ec95d23ba6265a6b737f89292a6

**Comment by Lsuper-King** [comment]
你好大佬 为什么我按照您的办法设置自动更新快捷指令 早上手机通知自动更新失败呢？![image](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/173053171/c5bfea35-d20f-4cc3-9fab-f9ae0c39d2ef)![image](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/173053171/87ff81bd-760b-40e8-9406-f15700509f1c)

**Comment by shankangk** [comment]
因为ios的自动化需要你解锁手机或者不设置密码才行，不然不能自动生效。你可以设置自动化每天打开微信或者进行其他什么操作的时候运行自动化即可。

**Comment by Lsuper-King** [comment]
> 因为ios的自动化需要你解锁手机或者不设置密码才行，不然不能自动生效。你可以设置自动化每天打开微信或者进行其他什么操作的时候运行自动化即可。

你好大佬，这个自动运行你说的这个我不知道该怎么操作，如果不设置自动运行会有什么影响？ 或者说我每天去小火箭里面手动更新可以吗？

**Comment by shankangk** [comment]
基本上影响没多大，偶尔去手动更新一下也是没问题的，这个自动化只是为了方便每天都自动去更新成最新的配置文件

**Comment by Lsuper-King** [comment]
> 基本上影响没多大，偶尔去手动更新一下也是没问题的，这个自动化只是为了方便每天都自动去更新成最新的配置文件

![image](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/173053171/7147626a-0ece-41e5-987e-50fd940758a8)![image](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/assets/173053171/811281b5-9689-4366-80c6-82a4919c9005)不好意思，大佬还得麻烦你 我自动化打开微信更新配置变成了最上面的那个配置 但是我用的懒人配置是中间的那个 这两个配置不一样，影响分流吗？ 我该用哪个好

**Comment by shankangk** [comment]
一般来说区别不大，都差不多

**Comment by Lsuper-King** [comment]
> 一般来说区别不大，都差不多
感谢🙏
