### ISSUE TITLE
请问能否同时更新多条规则呢？

### ISSUE THREAD

**Issue by Yb2S3Man** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#55]
我把所有规则的地址都放到Text段里面，但是更新的时候发现失败。是不能这样做吗？Mac小白，诚心请教。

谢谢。

**Comment by Johnshall** [comment]
看看这个
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/issues/41
