### ISSUE TITLE
请求在黑名单中加入迪士尼流媒体的ip

### ISSUE THREAD

**Issue by 4ppp44** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#57]
黑名单很好用，但是不能看迪士尼+就很难受

**Comment by 4ppp44** [comment]
域名在这里https://github.com/lingchenzi/app/blob/main/DisneyPlus_Domain

**Comment by Johnshall** [comment]
Thanks!
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/eed6b97737e9cdd3ae9fe88e6ee31b2a33b18bc0

**Comment by 4pease** [comment]
今天更新了规则怎么没有迪士尼啊

**Comment by 4ppp44** [comment]
> Thanks!
> 
> https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/eed6b97737e9cdd3ae9fe88e6ee31b2a33b18bc0

今天更新规则怎么还没有迪士尼啊

**Comment by 4ppp44** [comment]
> > Thanks!
> > [eed6b97](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/eed6b97737e9cdd3ae9fe88e6ee31b2a33b18bc0)
> 
> 今天更新规则怎么还没有迪士尼啊

用的是这个规则https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_banlist_ad.conf

**Comment by Johnshall** [comment]
黑名单里只是把 GFW List 里的域名代理了，没有引入 manual_proxy.txt 的内容。我过段时间改一改，最近太忙。你可以先用白名单。

**Comment by 4ppp44** [comment]
> 黑名单里只是把 GFW List 里的域名代理了，没有引入 manual_proxy.txt 的内容。我过段时间改一改，最近太忙。你可以先用白名单。

好的，感谢大佬！

**Comment by Johnshall** [comment]
OK了
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/0c2c5ebfb14a87155a6560b066ff51d4cd6a64d5

**Comment by 4ppp44** [comment]
> OK了
> [0c2c5eb](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/0c2c5ebfb14a87155a6560b066ff51d4cd6a64d5)

感谢！！！！
