### ISSUE TITLE
在配置文件中自行添加规则后会出现YouTube视频一直在加载中的问题 请问是怎么回事

### ISSUE THREAD

**Issue by H5Z0** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#59]

**Comment by H5Z0** [comment]
![image](https://user-images.githubusercontent.com/33372487/202651953-f2ff94df-eac8-4147-8d6a-b37f939ff537.jpeg)

**Comment by Johnshall** [comment]
不清楚，无法复现。
