### ISSUE TITLE
去广告

### ISSUE THREAD

**Issue by xinxin7741** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#6]
去广告是网页页面内还是软件的开屏广告？这个有点不太清楚，因为我的好多软件还是有开屏广告

**Comment by Johnshall** [comment]
本规则转译最新版本的 EasyList, Eaylist China, Peter Lowe 广告和隐私跟踪域名， 乘风规则为 SR 规则，通过匹配域名以达到去广告的目的。
  建议您开启https解密以实现更深层的广告过滤效果。
  由于目前的广告服务器不能仅仅通过匹配域名来识别并拦截，并且广告规则也并不能全面，所以您仍然会看到广告。
  如果您希望更深层的广告过滤，可以考虑采用专业的广告屏蔽应用。
  如果您还有疑问，可以继续留言。如果您认为我回答了您的问题，您可以关闭这个issue。

  祝您新年快乐！Johnshall 敬上

**Comment by c740030066** [comment]
sr_cnip_ad
国内直连 + 国外代理 去广告
能不能配置好 开启YouTube去广告脚本
我每次更新配置，都要手动打开
还有是不是去广告完整，要开始https解密，那每次更新是不是又要重新开启

**Comment by Forelsket520** [comment]
懒人配置含含策略组能把一个国外内外分去广告的规则组合在一起吗

**Comment by 1042187809** [comment]
你好，能不能出一个添加屏蔽广告规则的教程，有些网页还是会有广告。

**Comment by DrZevin** [comment]
打开之后b站视频打不开了
