### ISSUE TITLE
请问stash有没有方法用上这些规则

### ISSUE THREAD

**Issue by 4ppp44** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#61]
在github上搜了很多clash的规则，都不满意，这个是我目前用的最好的了，我想在stash上用，有没有方法

**Comment by Johnshall** [comment]
我不清楚能不能用，因为stash还挺贵的，我买不起。

**Comment by 4ppp44** [comment]
> 我不清楚能不能用，因为stash还挺贵的，我买不起。

这个是stash的格式https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EasyPrivacy/EasyPrivacy_Classical.yaml

**Comment by Johnshall** [comment]
应该可以直接套用clash的规则吧，那样可选余地就很大。比如 https://github.com/Loyalsoldier/clash-rules

**Comment by 4ppp44** [comment]
> 应该可以直接套用clash的规则吧，那样可选余地就很大。比如 https://github.com/Loyalsoldier/clash-rules

是的，我可以给你提供软件大佬

**Comment by Johnshall** [comment]
不用不用，只是调侃一下...主要是我个人比较忙，不太有时间和精力去做这个，另外同类的资源其实蛮多，也不是很有价值。

**Comment by 4ppp44** [comment]
> 不用不用，只是调侃一下...主要是我个人比较忙，不太有时间和精力去做这个，另外同类的资源其实蛮多，也不是很有价值。

好的，谢谢

**Comment by Johnshall** [comment]
生活不易，你也加油！

**Comment by 4ppp44** [comment]
> 生活不易，你也加油！

嗯嗯，加油

**Comment by Johnshall** [comment]
我不清楚，目前的规则不能用的吗？
https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/lazy_group.conf
这个规则可以用吗？
