### ISSUE TITLE
Mac OS  safari浏览器的翻译功能无法使用

### ISSUE THREAD

**Issue by momochina** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#62]
在任意加载完毕的英文页面，点击地址栏右侧翻译，选择“翻译为简体中文”，地址栏底部蓝色进度条一闪而过，翻译图标变成蓝色，翻译菜单里的“翻译为简体中文”变成灰色，页面上没有任何改变。
系统版本macOS 13，关闭代理则可以正常翻译。
iOS 则打开代理也可使用Safari自带翻译。

**Comment by Johnshall** [comment]
可不可以提供一下日志

**Comment by momochina** [comment]
1）怎么提供呢？电脑小白。
2）但我估计是mac os 13的锅，详见https://www.nuomiphp.com/t/635ce6fe1b62d87b8628817b.html      但我添加了绕过后还是没用，不知道是我的方法错了还是怎么。

**Comment by Johnshall** [comment]
你使用的是哪一个规则？

**Comment by momochina** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever#白名单过滤--广告

**Comment by Johnshall** [comment]
> 1）怎么提供呢？电脑小白。 2）但我估计是mac os 13的锅，详见https://www.nuomiphp.com/t/635ce6fe1b62d87b8628817b.html 但我添加了绕过后还是没用，不知道是我的方法错了还是怎么。

1. 在数据 -> 日志 -> 代理，打开日志记录，然后尽快使用 Safari 的翻译功能，看有哪些网址走了代理。
2. 白名单里 *.apple.com 都是直连的，应该不是这个问题。

**Comment by momochina** [comment]
[mac与ios.zip](https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/files/10073998/mac.ios.zip)
iOS和Mac上用的好像不是同一个翻译端口。

**Comment by Johnshall** [comment]
做得很好！但是我不是很方便读，可以麻烦将有价值的地址进行筛选（apple域名并且代理）贴在这里嘛？辛苦了

**Comment by momochina** [comment]
苹果的翻译地址是sequoia.apple.com，通过控制变量法实验我感觉应该不是你的规则的问题，应该是shadowrocket的问题，mac使用的话即使是本地节点也无法打开翻译，毕竟这个软件不是真正的mac版。
不然不可能同一套规则手机能用笔记本就不能用了，应该是软件问题。

**Comment by Johnshall** [comment]
确实，苹果有一些服务不遵循代理，或在代理的条件下会出现问题。
很有意义的一个讨论。

**Comment by shankangk** [comment]
配置文件设置忽略*.apple.com即可
