### ISSUE TITLE
关于外区apple ID登录播客，浏览还是无法加载问题

### ISSUE THREAD

**Issue by willgogo232** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#64]
大佬
请问我把你提到的那几个地址添加进去规则，为啥apple 播客还是无法处于无法加载的状态？

我把几位的规则整合去重了，把原来二级地址重新放到一级了，显得文件有点庞大
https://raw.githubusercontent.com/willgogo232/personalized/main/Combination?token=GHSAT0AAAAAAB3WQPPL7XQKGYNWFIGWDTVCY4FXIOA

**Comment by Johnshall** [comment]
也许播客有更多的新的域名或是ip歧视之类的？
你开全局代理可以加载吗？

**Comment by willgogo232** [comment]
都不行，就很奇怪，抓取IP看过，也都是正常的。最奇怪的事，偶尔还能加载  浏览  Tab

**Comment by Johnshall** [comment]
如果全局都不可以的话，应该是ip歧视之类的。可能需要原生ip的节点或者更多的认证。

**Comment by willgogo232** [comment]
感谢指点，我把那三个打开播客之后出现的站点全部指向美国节点，就正常了

**Comment by willgogo232** [comment]
已解决，把这些ip都指向美国节点
