### ISSUE TITLE
请问一下，如何更新最新的规则

### ISSUE THREAD

**Issue by clownwait** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#7]
设备为ios，已经扫码添加了规则并且已经使用了，如果后续您更新规则以后，我还需要再次扫描二维码去获取最新规则吗？还是直接从小火箭的远程文件点击使用配置即可下载最新规则？
第一次使用，希望能得到您的解答！感谢！

**Comment by clownwait** [comment]
好的，谢谢您的帮助

**Comment by inceptiongt** [comment]
> 您好！感谢您的提问！ 您可以在 Shadowrocket 主界面下方菜单里选择 配置 —> 本地文件 —> 点击规则 —> 在弹出的菜单中选择更新配置即可正常更新。 希望可以帮到您！如果还有困难请继续提问。 祝万事胜意！ Johnshall,敬上。

![image](https://user-images.githubusercontent.com/20478779/161746845-6f9709e2-6f3c-4232-9e9d-9e9efb1444cf.png)
如图有个“脚本订阅”功能，应该可以定时更新。点进去需要填个URL，填入本项目提供的url，提示“未能获得数据，格式不正确”。麻烦大佬提供个脚本订阅的URL，谢谢

**Comment by Johnshall** [comment]
> > 您好！感谢您的提问！ 您可以在 Shadowrocket 主界面下方菜单里选择 配置 —> 本地文件 —> 点击规则 —> 在弹出的菜单中选择更新配置即可正常更新。 希望可以帮到您！如果还有困难请继续提问。 祝万事胜意！ Johnshall,敬上。
> 
> ![image](https://user-images.githubusercontent.com/20478779/161746845-6f9709e2-6f3c-4232-9e9d-9e9efb1444cf.png) 如图有个“脚本订阅”功能，应该可以定时更新。点进去需要填个URL，填入本项目提供的url，提示“未能获得数据，格式不正确”。麻烦大佬提供个脚本订阅的URL，谢谢

这个功能似乎是更新脚本用的，不能订阅规则。
