### ISSUE TITLE
请问可以把 geoip.db 也传上来吗

### ISSUE THREAD

**Issue by GeorgeRudd** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#75]
不好意思，因为 https://github.com/Johnshall/v2ray-rules-dat 没开issue所以只能发这里了。
请问那个项目里面的 geosite.db 是根据 https://github.com/Loyalsoldier/v2ray-rules-dat 里面的 geosite.dat 转换过来的吗？
能不能把 geoip.db 也传上来呢 sing-box要用

刚又看到有个 https://github.com/Johnshall/sing-geosite/releases
请问和 https://github.com/Johnshall/v2ray-rules-dat 有区别吗

**Comment by Johnshall** [comment]
Q: 请问那个项目里面的 geosite.db 是根据 https://github.com/Loyalsoldier/v2ray-rules-dat 里面的 geosite.dat 转换过来的吗？
A: 是的。
Q: 能不能把 geoip.db 也传上来呢 sing-box要用
A: 没有兴趣，感觉哪边都不讨好。
Q: 刚又看到有个 https://github.com/Johnshall/sing-geosite/releases 请问和 https://github.com/Johnshall/v2ray-rules-dat 有区别吗
A: 两个完全不同的项目
