### ISSUE TITLE
更新一下Greatfire Analyzer

### ISSUE THREAD

**Issue by Potterli20** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#8]
已经停更https://github.com/Loyalsoldier/cn-blocked-domain

续以上项目
https://trli.coding.net/public/file/cn-blocked-domain/git/files/master/publish

**Comment by Johnshall** [comment]
感谢反馈！
为了保证上游库可控，我 fork 了 https://github.com/Loyalsoldier/cn-blocked-domain 并继续启动更新。详见：https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/eff0e9fefd1c2ff3e2e0deb5208202d7cb2864f7
祝万事胜意！
Johnshall 敬上

**Comment by Potterli20** [comment]
这个是我自己合并的域名
这个是中国域名
https://trli.coding.net/p/file/d/dns-hosts/git/lfs/master/dns-domain/blacklist_full.txt

这个是国际域名
https://trli.coding.net/p/file/d/dns-hosts/git/lfs/master/dns-domain/whitelist_full.txt

是24小时更新的

**Comment by Johnshall** [comment]
抱歉，可能是我的疏忽导致没有看到您的规则的生成方式与引用源。为了保证本项目的中立和透明，请问是否可以提供关于您规则的生成方式部分的代码？
并且，引用托管在 coding.net 的项目可能会增加不稳定性。
很希望您可以解答以上两个疑问，感谢！

**Comment by Potterli20** [comment]
> 抱歉，可能是我的疏忽导致没有看到您的规则的生成方式与引用源。为了保证本项目的中立和透明，请问是否可以提供关于您规则的生成方式部分的代码？
> 并且，引用托管在 coding.net 的项目可能会增加不稳定性。
> 很希望您可以解答以上两个疑问，感谢！

引用是在www.trli.club/list.txt，可以在那里搜关键词cnacc和gfwlist

托管在coding.net并不会增加不稳定性，你在github托管也是会增加不稳定性，所以托管没什么要求，国内可以用coding，国外可以用github和gitlab

**Comment by Johnshall** [comment]
> 

您好！
很抱歉我没有说明清晰，这里的“托管的稳定性”是指需要考虑规则的特殊性是否符合当地规范。
我也看了hezhijie0327规则，但是您没有提供您仓库中规则的生成方式，上游仍然不可控。

**Comment by Potterli20** [comment]
> > 
> 
> 您好！
> 很抱歉我没有说明清晰，这里的“托管的稳定性”是指需要考虑规则的特殊性是否符合当地规范。
> 我也看了hezhijie0327规则，但是您没有提供您仓库中规则的生成方式，上游仍然不可控。

我已经说了是基于hezhijie0327的脚本，但他那个比较少，我自己增加和优化了，目前我规则生成脚本是设置为私生的没有去提供。我提供了已经lists.txt列表里的域名

**Comment by Johnshall** [comment]
> > 您好！
> > 很抱歉我没有说明清晰，这里的“托管的稳定性”是指需要考虑规则的特殊性是否符合当地规范。
> > 我也看了hezhijie0327规则，但是您没有提供您仓库中规则的生成方式，上游仍然不可控。
> 
> 我已经说了是基于hezhijie0327的脚本，但他那个比较少，我自己增加和优化了，目前我规则生成脚本是设置为私生的没有去提供。我提供了已经lists.txt列表里的域名

真的很抱歉，为了保证项目的上游可控性和稳定性，我不能将您的项目进行合并。您可以自行fork本项目并根据许可证进行修改和发行。同时很感谢您指出上游库停止更新的情况。

谢谢您！祝万事顺遂。
Johnshall 敬上

**Comment by Johnshall** [comment]
> > 抱歉，可能是我的疏忽导致没有看到您的规则的生成方式与引用源。为了保证本项目的中立和透明，请问是否可以提供关于您规则的生成方式部分的代码？
> > 并且，引用托管在 coding.net 的项目可能会增加不稳定性。
> > 很希望您可以解答以上两个疑问，感谢！
> 
> 引用是在www.trli.club/list.txt，可以在那里搜关键词cnacc和gfwlist
> 
> 托管在coding.net并不会增加不稳定性，你在github托管也是会增加不稳定性，所以托管没什么要求，国内可以用coding，国外可以用github和gitlab
> 
> 脚本是基于hezhijie0327的脚本进行加减优化等

不幸被言中
https://www.zhihu.com/question/533388365
