### ISSUE TITLE
可以添加下解锁TIKTOK的规则吗，我自己添加了规则集，但是没有作用.

### ISSUE THREAD

**Issue by KXHLTD** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#84]

**Comment by Johnshall** [comment]
1. 由于解锁 Tiktok 需求不普遍，并且可能影响普通国内用户，为了普遍性不在官方规则里加入。
2. 没有起作用应该是配置错误，正确的添加方法请参考 https://github.com/Semporia/TikTok-Unlock
