### ISSUE TITLE
请问是否可以在lazy和top 500 whitelist里面加入wechat直连

### ISSUE THREAD

**Issue by cnChenKai** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#87]
因为微信改为wechat后服务器在新加坡，直连反而更快，是否可以在懒人和白名单500内加入wechat规则。
相关策略可以参考https://github.com/mu-bibai/ios_rule_script/tree/master/rule/Shadowrocket/WeChat

**Comment by Johnshall** [comment]
懒人配置中一直都有wechat走直连的规则集。
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/blob/release/lazy_group.conf#L139

**Comment by cnChenKai** [comment]
感谢，不好意思没有仔细查看，添麻烦了。

**Comment by csc-EricWu** [comment]
我想手动将RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list,DIRECT
这条规则在Shadowrocket 中改为代理，请问该怎么做？

**Comment by mu-bibai** [comment]
[DIRECT](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list,DIRECT)中的DIRECT改为PROXY

**Comment by mu-bibai** [comment]
> csc

[DIRECT](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list,DIRECT)中的DIRECT改为PROXY

**Comment by cnChenKai** [comment]
> 我想手动将RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list,DIRECT 这条规则在Shadowrocket 中改为代理，请问该怎么做？

[DIRECT](https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list,DIRECT)中的DIRECT改为PROXY
