### ISSUE TITLE
亚马逊视频支持

### ISSUE THREAD

**Issue by TonyMa68** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#88]
发现黑名单模式下无法观看amazon视频，我自己的处理是加一条代理规则，api.amazonvideo.com走代理，当然也可能需要其他规则，我不是特别在行，可以在后续版本中加上对于此平台的支持吗？

**Comment by Johnshall** [comment]
已将全部 Amazon 域名加入代理。
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/bf8869ef6c13d4946801ee8ff87b9ab6bb08389a

不过还是推荐在懒人规则-策略组中的 Amazon 选择代理。

**Comment by Johnshall** [comment]
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/commit/621d3b3f1b0b968593042d2d584f988316b4388e
已去除 *.cn 域名
