### ISSUE TITLE
能去除app内的广告吗

### ISSUE THREAD

**Issue by KangMz** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#9]
因为我用了下，打开知乎发现没有效果，好奇问一下。

**Comment by Johnshall** [comment]
请参考 https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/issues/6

**Comment by KangMz** [comment]
感谢回复，所以是主要去除网页广告，app应用内广告或者开屏广告是随缘，可以这样理解吗

**Comment by Johnshall** [comment]
大概可以这样理解，不过如果您抓取到了广告网站地址，欢迎您告知我或者直接pr！感谢！
