### ISSUE TITLE
想了解一下, 怎样可以和默认合并

### ISSUE THREAD

**Issue by ColinYYCC** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#92]
你好, 我希望可以和您直接联系,有很多问题想了解
可不可以和default 和 whitelist 合并, 又可以正常更新?

**Comment by Johnshall** [comment]
1. 有问题在这里提就好
2. fork项目，将build分支中 https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/blob/build/factory/template/sr_head.txt 改为默认文件的形式，release就好。

**Comment by ColinYYCC** [comment]
大神可以说的更直白吗~ 电脑小白~

**Comment by Johnshall** [comment]
1. 如何Fork和Release https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever#%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88
2. 如何修改文件请自行搜索

**Comment by ColinYYCC** [comment]
大神 那 v2rayN 里的geosite:category-ads-all 在小火箭里可以怎写?我沒看到他有 geosite~ 他只有geoip

**Comment by Johnshall** [comment]
小火箭不支持这种格式的。小火箭的规则格式类似于clash。

**Comment by ColinYYCC** [comment]
老师,那我想問一下, 你弄的规则可不可以把 easlylist / ublock 的 list 加进去

**Comment by Johnshall** [comment]
ublock是一个去广告软件。
EasyList规则已经包含了上述内容。
祝你新年快乐！
