### ISSUE TITLE
ios设备shadowrocket能访问youtube应用,但无法访问wotb应用？

### ISSUE THREAD

**Issue by fuyunjinglong** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#93]
大佬您好，有个问题困扰了我几个月，想咨询下您。shadowrocket都配置了，能正常访问youtube应用，但无法访问world of tank游戏应用，一直提示找不到 DNS 服务器位置(游戏官方解释https://asia.wargaming.net/support/zh_sg/products/wot/article/18995/)。我在DNS覆写里配置8.8.8.8和8.8.4.4，仍然不行，您看能不能帮我分析下，感谢

**Comment by Johnshall** [comment]
使用全局代理，wotb仍然显示找不到dns。我个人觉得是wotb有一些ip歧视吧。欢迎更多wotb玩家抓包投稿。
