### ISSUE TITLE
请教下有没有配置方面的教程，想实现一些功能

### ISSUE THREAD

**Issue by YPGen77** [Johnshall/Shadowrocket-ADBlock-Rules-Forever#96]
用您的规则很久了，很好用，但是个人可能还需要一些个性化的配置，又想根据您的项目每日更新，不知该如何实现

简单说就是想在使用您实时更新的top500规则上，根据个人使用习惯修改一些，且不随更新变化，不知该如何实现

**Comment by Johnshall** [comment]
看看这个
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/tree/build/factory
https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/tree/build#问题反馈
